import { Routes } from '@angular/router';
import { PageSeo } from './shared/seo';

// GENERATED by scripts/gen-pages.mjs from the legacy site/** sources — do not hand-edit.
// SEO strings are translated via @angular/localize (custom $localize ids → src/locale/messages.en.xlf).
// Page body content + chrome are locale-gated by LOCALE_ID in the components/templates.
export const routes: Routes = [
  {
    path: 'admin',
    loadComponent: () =>
      import('./pages/admin/admin.component').then((m) => m.AdminComponent),
    title: 'Admin | Faunapoolen',
    data: {
      seo: {
        path: '/admin/',
        description: 'Sign in to Faunapoolen admin.',
        private: true,
      } satisfies PageSeo,
    },
  },
  {
    path: '',
    loadComponent: () => import('./pages/home/home.component').then((m) => m.HomeComponent),
    title: $localize`:@@home.title:Faunapoolen | Ekologisk pool och vattenlandskap utan klor`,
    data: {
      seo: {
        path: '/',
        keywords: $localize`:@@home.keywords:ekologisk pool, simdamm, pool utan klor, vattenlandskap, vattenfall trädgård, fontän, koidamm, regnvatteninsamling, naturlig trädgårdsdesign`,
        description: $localize`:@@home.description:Faunapoolen designar ekologisk pool, simdamm, vattenfall, fontän och vattenlandskap som smälter in naturligt i din trädgård.`,
        ogTitle: $localize`:@@home.ogTitle:Faunapoolen | Ekologisk pool och vattenlandskap`,
        ogDescription: $localize`:@@home.ogDescription:Ekologisk pool, simdamm, fontän, koidamm och vattenfall för naturliga svenska trädgårdar.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'about',
    loadComponent: () => import('./pages/about/about.component').then((m) => m.AboutComponent),
    title: $localize`:@@about.title:Om Faunapoolen | Ekologiska pooler och vattenlandskap`,
    data: {
      seo: {
        path: '/about/',
        keywords: $localize`:@@about.keywords:ekologisk pool, organisk pool, pool utan klor, vattenlandskap, miljövänlig pool, naturlig trädgårdsdesign`,
        description: $localize`:@@about.description:Lär känna Faunapoolen och vårt arbete med ekologisk pool, organisk pool och hållbara vattenlandskap utan klor i svenska trädgårdar.`,
        ogTitle: $localize`:@@about.ogTitle:Om Faunapoolen`,
        ogDescription: $localize`:@@about.ogDescription:Faunapoolen skapar ekologiska pooler, organiska pooler och naturliga vattenlandskap utan klor.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'services',
    loadComponent: () => import('./pages/services/services.component').then((m) => m.ServicesComponent),
    title: $localize`:@@services.title:Tjänster | Naturpool, koidamm, fontän och vattenfall`,
    data: {
      seo: {
        path: '/services/',
        keywords: $localize`:@@services.keywords:ekologisk pool, koidamm, fontän, vattenfall trädgård, regnvatteninsamling, trädgårdsskötsel, vattenlandskap`,
        description: $localize`:@@services.description:Utforska våra tjänster för ekologisk pool, koidamm, fontän, vattenfall i trädgård, regnvatteninsamling och trädgårdsskötsel.`,
        ogTitle: $localize`:@@services.ogTitle:Faunapoolens tjänster`,
        ogDescription: $localize`:@@services.ogDescription:Ekologisk pool, koidamm, fontän, vattenfall, regnvatteninsamling och trädgårdsskötsel.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'pricing',
    loadComponent: () => import('./pages/pricing/pricing.component').then((m) => m.PricingComponent),
    title: $localize`:@@pricing.title:Priser | Ekologisk pool, fontän, koidamm och vattenfall`,
    data: {
      seo: {
        path: '/pricing/',
        keywords: $localize`:@@pricing.keywords:ekologisk pool pris, fontän pris, koidamm, vattenfall trädgård, regnvatteninsamling, trädgårdsskötsel, simdamm`,
        description: $localize`:@@pricing.description:Se prisnivåer för ekologisk pool, fontän, koidamm, vattenfall, regnvatteninsamling och trädgårdsskötsel från Faunapoolen.`,
        ogTitle: $localize`:@@pricing.ogTitle:Priser från Faunapoolen`,
        ogDescription: $localize`:@@pricing.ogDescription:Prisnivåer för ekologisk pool, fontän, koidamm, vattenfall och hållbara vattenlandskap.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'contact',
    loadComponent: () => import('./pages/contact/contact.component').then((m) => m.ContactComponent),
    title: $localize`:@@contact.title:Kontakta Faunapoolen | Ekologisk pool och vattenlandskap`,
    data: {
      seo: {
        path: '/contact/',
        keywords: $localize`:@@contact.keywords:ekologisk pool, simdamm, pool utan klor, vattenlandskap, fontän, koidamm, naturlig trädgårdsdesign`,
        description: $localize`:@@contact.description:Kontakta Faunapoolen för rådgivning om ekologisk pool, simdamm, vattenlandskap, fontän, koidamm och pool utan klor.`,
        ogTitle: $localize`:@@contact.ogTitle:Kontakta Faunapoolen`,
        ogDescription: $localize`:@@contact.ogDescription:Rådgivning om ekologisk pool, simdamm, vattenlandskap, fontän, koidamm och pool utan klor.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'suppliers',
    loadComponent: () => import('./pages/suppliers/suppliers.component').then((m) => m.SuppliersComponent),
    title: $localize`:@@suppliers.title:Leverantörer | Hållbara vattenlandskap och natursten`,
    data: {
      seo: {
        path: '/suppliers/',
        keywords: $localize`:@@suppliers.keywords:vattenlandskap, naturlig trädgårdsdesign, vattenväxter, natursten, koidamm, vattenfall trädgård, fontän`,
        description: $localize`:@@suppliers.description:Våra leverantörer hjälper oss skapa hållbara vattenlandskap med natursten, vattenväxter, Aquascape-system och naturlig trädgårdsdesign.`,
        ogTitle: $localize`:@@suppliers.ogTitle:Faunapoolens leverantörer`,
        ogDescription: $localize`:@@suppliers.ogDescription:Hållbara leverantörer för vattenlandskap, natursten, vattenväxter och naturlig trädgårdsdesign.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'sweden-expert-naturpooler-biopooler-ecopooler-kemikaliefria-pooler-baddammar',
    loadComponent: () => import('./pages/sweden-expert-naturpooler-biopooler-ecopooler-kemikaliefria-pooler-baddammar/sweden-expert-naturpooler-biopooler-ecopooler-kemikaliefria-pooler-baddammar.component').then((m) => m.SwedenExpertNaturpoolerBiopoolerEcopoolerKemikaliefriaPoolerBaddammarComponent),
    title: $localize`:@@sweden_expert_naturpooler_biopooler_ecopooler_kemikaliefria_pooler_baddammar.title:Expert på naturpool, biopool och baddamm i Sverige | Faunapoolen`,
    data: {
      seo: {
        path: '/sweden-expert-naturpooler-biopooler-ecopooler-kemikaliefria-pooler-baddammar/',
        keywords: $localize`:@@sweden_expert_naturpooler_biopooler_ecopooler_kemikaliefria_pooler_baddammar.keywords:ekologisk pool, pool utan klor, miljövänlig pool, organisk pool, simdamm, vattenlandskap, biopool`,
        description: $localize`:@@sweden_expert_naturpooler_biopooler_ecopooler_kemikaliefria_pooler_baddammar.description:Sveriges expert på naturpool, biopool och baddamm. Vi designar och bygger kemikaliefria pooler och vattenlandskap utan klor för hållbara trädgårdar.`,
        ogTitle: $localize`:@@sweden_expert_naturpooler_biopooler_ecopooler_kemikaliefria_pooler_baddammar.ogTitle:Expert på naturpooler i Sverige`,
        ogDescription: $localize`:@@sweden_expert_naturpooler_biopooler_ecopooler_kemikaliefria_pooler_baddammar.ogDescription:Naturpooler, biopooler, ekologisk pool och vattenlandskap utan klor för svenska trädgårdar.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'nature-pools.html',
    loadComponent: () => import('./pages/nature-pools/nature-pools.component').then((m) => m.NaturePoolsComponent),
    title: $localize`:@@nature_pools.title:Naturpool utan klor – skräddarsydd och byggd av oss | Faunapoolen`,
    data: {
      seo: {
        path: '/nature-pools.html',
        keywords: $localize`:@@nature_pools.keywords:ekologisk pool, pool utan klor, miljövänlig pool, organisk pool, simdamm, vattenlandskap, naturlig trädgårdsdesign`,
        description: $localize`:@@nature_pools.description:Vi bygger din naturpool utan klor – skräddarsydd design, biologisk filtrering och rent, klart vatten. Få offert och personlig rådgivning hela vägen.`,
        ogTitle: $localize`:@@nature_pools.ogTitle:Naturpool och ekologisk pool`,
        ogDescription: $localize`:@@nature_pools.ogDescription:Ekologisk pool med klart vatten utan klor, biologisk filtrering och naturlig trädgårdsdesign.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/nature-pools-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'koi-pond-series.html',
    loadComponent: () => import('./pages/koi-pond-series/koi-pond-series.component').then((m) => m.KoiPondSeriesComponent),
    title: $localize`:@@koi_pond_series.title:Koidamm | Levande vattenlandskap för trädgården`,
    data: {
      seo: {
        path: '/koi-pond-series.html',
        keywords: $localize`:@@koi_pond_series.keywords:koidamm, vattenlandskap, naturlig trädgårdsdesign, miljövänlig pool, damm, biologisk filtrering`,
        description: $localize`:@@koi_pond_series.description:Skapa en frisk koidamm med klart vatten, biologisk balans och naturlig design som ger liv åt trädgården året runt.`,
        ogTitle: $localize`:@@koi_pond_series.ogTitle:Koidamm från Faunapoolen`,
        ogDescription: $localize`:@@koi_pond_series.ogDescription:Koidamm med klart vatten, biologisk balans och naturlig design för trädgården.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/koi-pond-series-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'swim-series.html',
    loadComponent: () => import('./pages/swim-series/swim-series.component').then((m) => m.SwimSeriesComponent),
    title: $localize`:@@swim_series.title:Swim-serien | Simdamm och pool utan klor`,
    data: {
      seo: {
        path: '/swim-series.html',
        keywords: $localize`:@@swim_series.keywords:simdamm, pool utan klor, ekologisk pool, organisk pool, miljövänlig pool, vattenlandskap, naturlig pool`,
        description: $localize`:@@swim_series.description:Swim-serien är en simdamm för dig som vill ha en riktig simtur i kristallklart vatten utan klor, kemikalier eller traditionell poolkänsla.`,
        ogTitle: $localize`:@@swim_series.ogTitle:Swim-serien från Faunapoolen`,
        ogDescription: $localize`:@@swim_series.ogDescription:Simdamm och pool utan klor för en naturlig simupplevelse i trädgården.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/swim-series-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'waterfront-series.html',
    loadComponent: () => import('./pages/waterfront-series/waterfront-series.component').then((m) => m.WaterfrontSeriesComponent),
    title: $localize`:@@waterfront_series.title:Waterfront-serien | Storskalig simdamm utan klor`,
    data: {
      seo: {
        path: '/waterfront-series.html',
        keywords: $localize`:@@waterfront_series.keywords:simdamm, ekologisk pool, pool utan klor, vattenlandskap, organisk pool, miljövänlig pool`,
        description: $localize`:@@waterfront_series.description:Waterfront-serien skapar en exklusiv simdamm och ekologisk pool med biologisk filtrering, naturligt vatten och storskaligt vattenlandskap.`,
        ogTitle: $localize`:@@waterfront_series.ogTitle:Waterfront-serien från Faunapoolen`,
        ogDescription: $localize`:@@waterfront_series.ogDescription:Storskalig simdamm och ekologisk pool med naturligt vatten utan klor.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/waterfront-series-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'plunge-series.html',
    loadComponent: () => import('./pages/plunge-series/plunge-series.component').then((m) => m.PlungeSeriesComponent),
    title: $localize`:@@plunge_series.title:Plunge-serien | Organisk pool och naturligt dopp`,
    data: {
      seo: {
        path: '/plunge-series.html',
        keywords: $localize`:@@plunge_series.keywords:organisk pool, pool utan klor, ekologisk pool, simdamm, miljövänlig pool, vattenlandskap`,
        description: $localize`:@@plunge_series.description:Plunge-serien är en kompakt organisk pool för kalla dopp, avkoppling och naturligt vatten utan klor i trädgården.`,
        ogTitle: $localize`:@@plunge_series.ogTitle:Plunge-serien från Faunapoolen`,
        ogDescription: $localize`:@@plunge_series.ogDescription:Kompakt organisk pool för kalla dopp, avkoppling och naturligt vatten utan klor.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/plunge-series-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'pond-packages-landing.html',
    loadComponent: () => import('./pages/pond-packages-landing/pond-packages-landing.component').then((m) => m.PondPackagesLandingComponent),
    title: $localize`:@@pond_packages_landing.title:Naturpoolpaket | Simdamm och ekologisk pool utan klor`,
    data: {
      seo: {
        path: '/pond-packages-landing.html',
        keywords: $localize`:@@pond_packages_landing.keywords:simdamm, ekologisk pool, organisk pool, pool utan klor, miljövänlig pool, naturpoolpaket, vattenlandskap`,
        description: $localize`:@@pond_packages_landing.description:Upptäck Faunapoolens naturpoolpaket för simdamm, ekologisk pool och organisk pool med klart vatten utan klor eller starka kemikalier.`,
        ogTitle: $localize`:@@pond_packages_landing.ogTitle:Naturpoolpaket från Faunapoolen`,
        ogDescription: $localize`:@@pond_packages_landing.ogDescription:Simdamm, ekologisk pool och organisk pool med klart vatten utan klor.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/pond-packages-landing-og.jpg',
      } satisfies PageSeo,
    },
  },
  {
    path: 'campaigns/pond-packages',
    loadComponent: () => import('./pages/campaigns/pond-packages/pond-packages.component').then((m) => m.PondPackagesCampaignComponent),
    title: 'Bada i klart, naturligt vatten hemma | Naturpool',
    data: {
      seo: {
        path: '/campaigns/pond-packages/',
        description: 'Få en naturpool med biologisk rening, anpassad till din trädgård. Lämna dina uppgifter så svarar Faunapoolen inom 48 timmar.',
        ogTitle: 'Bada i klart, naturligt vatten hemma.',
        ogDescription: 'Naturpool med biologisk rening, anpassad till din trädgård och svenska årstider.',
        ogImage: 'https://faunapoolen.se/assets/images/og/pond-packages-landing-og.jpg',
        noindex: true,
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog',
    loadComponent: () => import('./pages/blog/blog-index.component').then((m) => m.BlogIndexComponent),
    title: $localize`:@@blog_index.title:Blogg | Ekologisk pool, vattenlandskap och trädgård`,
    data: {
      seo: {
        path: '/blog/',
        keywords: $localize`:@@blog_index.keywords:ekologisk pool, pool utan klor, simdamm, koidamm, vattenfall trädgård, fontän, regnvatteninsamling, vattenlandskap`,
        description: $localize`:@@blog_index.description:Läs guider om ekologisk pool, pool utan klor, simdamm, vattenfall, fontän, koidamm, regnvatteninsamling och naturlig trädgårdsdesign.`,
        ogTitle: $localize`:@@blog_index.ogTitle:Faunapoolens blogg`,
        ogDescription: $localize`:@@blog_index.ogDescription:Guider om ekologisk pool, pool utan klor, koidamm, vattenfall, fontän och vattenlandskap.`,
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/5-common-problems-installing-a-nature-pool.html',
    loadComponent: () => import('./pages/blog/posts/5-common-problems-installing-a-nature-pool.component').then((m) => m.Page5CommonProblemsInstallingANaturePoolComponent),
    title: $localize`:@@5_common_problems_installing_a_nature_pool.title:Problem med naturpool | Så lyckas du med ekologisk pool`,
    data: {
      seo: {
        path: '/blog/posts/5-common-problems-installing-a-nature-pool.html',
        keywords: $localize`:@@5_common_problems_installing_a_nature_pool.keywords:ekologisk pool, pool utan klor, miljövänlig pool, organisk pool, simdamm, naturpool problem, vattenlandskap`,
        description: $localize`:@@5_common_problems_installing_a_nature_pool.description:Undvik vanliga misstag när du planerar ekologisk pool eller pool utan klor: balans, placering, tätning, cirkulation och rätt växter.`,
        ogTitle: $localize`:@@5_common_problems_installing_a_nature_pool.ogTitle:Vanliga problem med naturpool`,
        ogDescription: $localize`:@@5_common_problems_installing_a_nature_pool.ogDescription:Undvik misstag med ekologisk pool och pool utan klor: balans, placering, tätning och cirkulation.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/5-common-problems-installing-a-nature-pool-og.jpg',
        ogType: 'article',
        datePublished: '2026-04-14',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/algae-control-and-maintenance-tips.html',
    loadComponent: () => import('./pages/blog/posts/algae-control-and-maintenance-tips.component').then((m) => m.AlgaeControlAndMaintenanceTipsComponent),
    title: $localize`:@@algae_control_and_maintenance_tips.title:Algkontroll | Skötsel av koidamm och vattenlandskap`,
    data: {
      seo: {
        path: '/blog/posts/algae-control-and-maintenance-tips.html',
        keywords: $localize`:@@algae_control_and_maintenance_tips.keywords:koidamm, vattenlandskap, trädgårdsskötsel, fontän, algkontroll, biologisk filtrering, naturlig trädgårdsdesign`,
        description: $localize`:@@algae_control_and_maintenance_tips.description:Få råd om algkontroll, biologisk balans och trädgårdsskötsel för koidamm, fontän och hållbara vattenlandskap.`,
        ogTitle: $localize`:@@algae_control_and_maintenance_tips.ogTitle:Algkontroll och trädgårdsskötsel`,
        ogDescription: $localize`:@@algae_control_and_maintenance_tips.ogDescription:Råd om algkontroll, biologisk balans och skötsel för koidamm, fontän och vattenlandskap.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/algae-control-and-maintenance-tips-og.jpg',
        ogType: 'article',
        datePublished: '2025-08-05',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/build-your-own-nature-pool.html',
    loadComponent: () => import('./pages/blog/posts/build-your-own-nature-pool.component').then((m) => m.BuildYourOwnNaturePoolComponent),
    title: $localize`:@@build_your_own_nature_pool.title:Faunapoolen | Naturpooler, biopooler, ecopooler och kemikaliefria pooler - design och konstruktion av experter i Sverige`,
    data: {
      seo: {
        path: '/blog/posts/build-your-own-nature-pool.html',
        keywords: $localize`:@@build_your_own_nature_pool.keywords:naturpool, skräddarsydda pooler, bygga naturpool, kemikaliefri pool, naturlig pool, ekologisk pool, vattenlandskap, hållbar pool, pooldesign, poolinstallation, trädgårdsdesign, poolunderhåll, kemikaliefria vattenlandskap, fontäner, aquascape, aquascape pooler`,
        description: $localize`:@@build_your_own_nature_pool.description:Vi designar och bygger naturpooler, biopooler, ekopooler, kemikaliefria pooler och baddammar.`,
        ogTitle: $localize`:@@build_your_own_nature_pool.ogTitle:Faunapoolen`,
        ogDescription: $localize`:@@build_your_own_nature_pool.ogDescription:Vi designar och bygger naturpooler, biopooler, ekopooler, kemikaliefria pooler och baddammar.`,
        ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
    loadComponent: () => import('./pages/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.component').then((m) => m.CanIUseWaterStorageSolutionsWhenTraditionalWellsArentAnOptionComponent),
    title: $localize`:@@can_i_use_water_storage_solutions_when_traditional_wells_arent_an_option.title:Regnvatteninsamling | Vattenlagring för hållbar trädgård`,
    data: {
      seo: {
        path: '/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
        keywords: $localize`:@@can_i_use_water_storage_solutions_when_traditional_wells_arent_an_option.keywords:regnvatteninsamling, vattenlandskap, naturlig trädgårdsdesign, miljövänlig pool, damm, vattenlagring`,
        description: $localize`:@@can_i_use_water_storage_solutions_when_traditional_wells_arent_an_option.description:Lär dig hur regnvatteninsamling och vattenlagring kan försörja trädgård, damm och vattenlandskap när traditionella brunnar inte räcker.`,
        ogTitle: $localize`:@@can_i_use_water_storage_solutions_when_traditional_wells_arent_an_option.ogTitle:Regnvatteninsamling och vattenlagring`,
        ogDescription: $localize`:@@can_i_use_water_storage_solutions_when_traditional_wells_arent_an_option.ogDescription:Vattenlagring och regnvatteninsamling för trädgård, damm och hållbara vattenlandskap.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option-og.jpg',
        ogType: 'article',
        datePublished: '2025-10-21',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
    loadComponent: () => import('./pages/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.component').then((m) => m.CreatingHarmonyIntergratingWaterFeaturesWithYourLandscapeComponent),
    title: $localize`:@@creating_harmony_intergrating_water_features_with_your_landscape.title:Vattenlandskap | Vattenfall, koidamm och fontän`,
    data: {
      seo: {
        path: '/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
        keywords: $localize`:@@creating_harmony_intergrating_water_features_with_your_landscape.keywords:vattenlandskap, vattenfall trädgård, koidamm, fontän, naturlig trädgårdsdesign, miljövänlig pool`,
        description: $localize`:@@creating_harmony_intergrating_water_features_with_your_landscape.description:Så integrerar du vattenfall i trädgård, koidamm och fontän i en naturlig trädgårdsdesign med ekologisk balans.`,
        ogTitle: $localize`:@@creating_harmony_intergrating_water_features_with_your_landscape.ogTitle:Vattenlandskap i trädgården`,
        ogDescription: $localize`:@@creating_harmony_intergrating_water_features_with_your_landscape.ogDescription:Integrera vattenfall, koidamm och fontän i en naturlig trädgårdsdesign.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/creating-harmony-intergrating-water-features-with-your-landscape-og.jpg',
        ogType: 'article',
        datePublished: '2025-09-30',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/difference-between-normal-pool-and-natural-pool.html',
    loadComponent: () => import('./pages/blog/posts/difference-between-normal-pool-and-natural-pool.component').then((m) => m.DifferenceBetweenNormalPoolAndNaturalPoolComponent),
    title: $localize`:@@difference_between_normal_pool_and_natural_pool.title:Faunapoolen | Naturpooler, biopooler, ecopooler och kemikaliefria pooler - design och konstruktion av experter i Sverige`,
    data: {
      seo: {
        path: '/blog/posts/difference-between-normal-pool-and-natural-pool.html',
        keywords: $localize`:@@difference_between_normal_pool_and_natural_pool.keywords:naturpool, skräddarsydda pooler, bygga naturpool, kemikaliefri pool, naturlig pool, ekologisk pool, vattenlandskap, hållbar pool, pooldesign, poolinstallation, trädgårdsdesign, poolunderhåll, kemikaliefria vattenlandskap, fontäner, aquascape, aquascape pooler`,
        description: $localize`:@@difference_between_normal_pool_and_natural_pool.description:Vi designar och bygger naturpooler, biopooler, ekopooler, kemikaliefria pooler och baddammar.`,
        ogTitle: $localize`:@@difference_between_normal_pool_and_natural_pool.ogTitle:Faunapoolen`,
        ogDescription: $localize`:@@difference_between_normal_pool_and_natural_pool.ogDescription:Vi designar och bygger naturpooler, biopooler, ekopooler, kemikaliefria pooler och baddammar.`,
        ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
    loadComponent: () => import('./pages/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.component').then((m) => m.HowFaunapoolenHelpsGolfClubsManagePondsLakesAndStreamsComponent),
    title: $localize`:@@how_faunapoolen_helps_golf_clubs_manage_ponds_lakes_and_streams.title:Vattenlandskap för golfbanor | Dammar, sjöar och bäckar`,
    data: {
      seo: {
        path: '/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
        keywords: $localize`:@@how_faunapoolen_helps_golf_clubs_manage_ponds_lakes_and_streams.keywords:vattenlandskap, damm, regnvatteninsamling, naturlig trädgårdsdesign, vattenhantering, miljövänlig pool`,
        description: $localize`:@@how_faunapoolen_helps_golf_clubs_manage_ponds_lakes_and_streams.description:Faunapoolen hjälper golfklubbar med vattenlandskap, dammar, sjöar, bäckar och hållbar vattenhantering för funktion och estetik.`,
        ogTitle: $localize`:@@how_faunapoolen_helps_golf_clubs_manage_ponds_lakes_and_streams.ogTitle:Vattenlandskap för golfbanor`,
        ogDescription: $localize`:@@how_faunapoolen_helps_golf_clubs_manage_ponds_lakes_and_streams.ogDescription:Hållbar skötsel och design av dammar, sjöar, bäckar och vattenlandskap på golfbanor.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams-og.jpg',
        ogType: 'article',
        datePublished: '2026-03-10',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/how-filtering-works-with-nature-pools.html',
    loadComponent: () => import('./pages/blog/posts/how-filtering-works-with-nature-pools.component').then((m) => m.HowFilteringWorksWithNaturePoolsComponent),
    title: $localize`:@@how_filtering_works_with_nature_pools.title:Så filtreras en ekologisk pool utan klor`,
    data: {
      seo: {
        path: '/blog/posts/how-filtering-works-with-nature-pools.html',
        keywords: $localize`:@@how_filtering_works_with_nature_pools.keywords:ekologisk pool, pool utan klor, simdamm, organisk pool, biologisk filtrering, miljövänlig pool`,
        description: $localize`:@@how_filtering_works_with_nature_pools.description:Förstå hur biologisk filtrering renar en ekologisk pool, simdamm eller organisk pool utan klor och starka kemikalier.`,
        ogTitle: $localize`:@@how_filtering_works_with_nature_pools.ogTitle:Filtrering i ekologisk pool`,
        ogDescription: $localize`:@@how_filtering_works_with_nature_pools.ogDescription:Så renas ekologisk pool, simdamm och organisk pool med biologisk filtrering utan klor.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/how-filtering-works-with-nature-pools-og.jpg',
        ogType: 'article',
        datePublished: '2025-07-08',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/pool-conversions.html',
    loadComponent: () => import('./pages/blog/posts/pool-conversions.component').then((m) => m.PoolConversionsComponent),
    title: $localize`:@@pool_conversions.title:Konvertera pool | Från klorpool till organisk pool`,
    data: {
      seo: {
        path: '/blog/posts/pool-conversions.html',
        keywords: $localize`:@@pool_conversions.keywords:organisk pool, pool utan klor, ekologisk pool, simdamm, poolkonvertering, miljövänlig pool`,
        description: $localize`:@@pool_conversions.description:Se hur en traditionell pool kan konverteras till organisk pool, simdamm eller ekologisk pool med naturlig filtrering utan klor.`,
        ogTitle: $localize`:@@pool_conversions.ogTitle:Konvertera pool till organisk pool`,
        ogDescription: $localize`:@@pool_conversions.ogDescription:Från klorpool till organisk pool, simdamm eller ekologisk pool med naturlig filtrering.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/pool-conversions-og.jpg',
        ogType: 'article',
        datePublished: '2026-01-27',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/small-features-for-small-spaces.html',
    loadComponent: () => import('./pages/blog/posts/small-features-for-small-spaces.component').then((m) => m.SmallFeaturesForSmallSpacesComponent),
    title: $localize`:@@small_features_for_small_spaces.title:Vattenfall och fontän för liten trädgård`,
    data: {
      seo: {
        path: '/blog/posts/small-features-for-small-spaces.html',
        keywords: $localize`:@@small_features_for_small_spaces.keywords:vattenfall trädgård, fontän, koidamm, regnvatteninsamling, naturlig trädgårdsdesign, vattenlandskap`,
        description: $localize`:@@small_features_for_small_spaces.description:Små trädgårdar kan rymma vattenfall, fontän, minidamm och regnvatteninsamling med smart naturlig trädgårdsdesign.`,
        ogTitle: $localize`:@@small_features_for_small_spaces.ogTitle:Vattenfall och fontän för små ytor`,
        ogDescription: $localize`:@@small_features_for_small_spaces.ogDescription:Vattenfall, fontän, minidamm och regnvatteninsamling för liten trädgård.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/small-features-for-small-spaces-og.jpg',
        ogType: 'article',
        datePublished: '2025-09-02',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/sports-stars-natural-ponds.html',
    loadComponent: () => import('./pages/blog/posts/sports-stars-natural-ponds.component').then((m) => m.SportsStarsNaturalPondsComponent),
    title: $localize`:@@sports_stars_natural_ponds.title:Simdamm för återhämtning | Pool utan klor`,
    data: {
      seo: {
        path: '/blog/posts/sports-stars-natural-ponds.html',
        keywords: $localize`:@@sports_stars_natural_ponds.keywords:simdamm, pool utan klor, ekologisk pool, organisk pool, miljövänlig pool, kallbad`,
        description: $localize`:@@sports_stars_natural_ponds.description:Därför väljer idrottare simdamm och pool utan klor för återhämtning, kallbad och naturligt vatten i hemmiljö.`,
        ogTitle: $localize`:@@sports_stars_natural_ponds.ogTitle:Simdamm för återhämtning`,
        ogDescription: $localize`:@@sports_stars_natural_ponds.ogDescription:Simdamm och pool utan klor för återhämtning, kallbad och naturligt vatten hemma.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/sports-stars-natural-ponds-og.jpg',
        ogType: 'article',
        datePublished: '2025-11-18',
      } satisfies PageSeo,
    },
  },
  {
    path: 'blog/posts/why-you-should-get-a-natural-pool.html',
    loadComponent: () => import('./pages/blog/posts/why-you-should-get-a-natural-pool.component').then((m) => m.WhyYouShouldGetANaturalPoolComponent),
    title: $localize`:@@why_you_should_get_a_natural_pool.title:Varför välja ekologisk pool och pool utan klor`,
    data: {
      seo: {
        path: '/blog/posts/why-you-should-get-a-natural-pool.html',
        keywords: $localize`:@@why_you_should_get_a_natural_pool.keywords:ekologisk pool, pool utan klor, miljövänlig pool, organisk pool, simdamm, naturlig trädgårdsdesign`,
        description: $localize`:@@why_you_should_get_a_natural_pool.description:En ekologisk pool ger bad utan klor, låg kemikalieanvändning, naturlig design och en miljövänlig pool som smälter in i trädgården.`,
        ogTitle: $localize`:@@why_you_should_get_a_natural_pool.ogTitle:Varför välja ekologisk pool`,
        ogDescription: $localize`:@@why_you_should_get_a_natural_pool.ogDescription:Bad utan klor, låg kemikalieanvändning och naturlig design med en miljövänlig pool.`,
        ogImage: 'https://faunapoolen.se/assets/images/og/why-you-should-get-a-natural-pool-og.jpg',
        ogType: 'article',
        datePublished: '2025-06-12',
      } satisfies PageSeo,
    },
  },
  {
    path: '**',
    loadComponent: () =>
      import('./pages/not-found/not-found.component').then((m) => m.NotFoundComponent),
    title: $localize`:@@notfound.title:Sidan kunde inte hittas | Faunapoolen`,
    data: {
      seo: {
        path: '/404',
        description: $localize`:@@notfound.description:Sidan kunde inte hittas.`,
        noindex: true,
      } satisfies PageSeo,
    },
  },
];
