import type { FaunapoolenGuideId } from './faunapoolen-content';
import type { PageSeo } from '../../shared/seo';
export interface BlogArticle {
  readonly id: FaunapoolenGuideId;
  readonly title: string;
  readonly intro: string;
  readonly image: string;
  readonly related: readonly FaunapoolenGuideId[];
  readonly seo: PageSeo & { title: string };
}
export const BLOG_ARTICLES: readonly BlogArticle[] = [
  {
    id: 'build',
    title: $localize`:@@blog.build.title:Building a nature pool – how to do it yourself`,
    intro: $localize`:@@blog.build.intro:Building a nature pool yourself is a dream for many who want to create a unique, eco-friendly, and harmonious place in their garden. A nature pool not only offers a swimming experience free from chemicals but also becomes an aesthetic part of the garden that blends into nature. Constructing a nature pool can seem like a big challenge, but it is possible with the right planning and knowledge. In this guide, you will learn how to do it, what risks exist, and how to avoid common mistakes.`,
    image: '/assets/images/blog/blog-post-mood-image-1.jpg',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.build.seo.title:Faunapoolen | nature pools, bio pools, eco pools, and chemical-free pools - design and construction by experts in Sweden`,
      path: '/blog/posts/build-your-own-nature-pool.html',
      keywords: $localize`:@@blog.build.seo.keywords:nature pool, custom pools, build nature pool, chemical-free pool, natural pool, organic pool, water landscape, sustainable pool, pool design, pool installation, garden design, pool maintenance, chemical-free water landscapes, fountains, aquascape, aquascape pools`,
      description: $localize`:@@blog.build.seo.description:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogTitle: $localize`:@@blog.build.seo.ogTitle:Faunapoolen`,
      ogDescription: $localize`:@@blog.build.seo.ogDescription:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      enPath: '/en/blog/posts/build-your-own-nature-pool.html',
      daPath: '/da/blog/posts/build-your-own-nature-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'difference',
    title: $localize`:@@blog.difference.title:Difference between a natural pool and a regular pool – which one should you choose?`,
    intro: $localize`:@@blog.difference.intro:Having a pool at home is a dream for many. It transforms the garden into a place for relaxation, fun, and refreshing dips on hot summer days. But when choosing a pool, there is an important question to ask: should you build a natural pool or a traditional pool? Both options have their advantages, but if you want a sustainable pool without chemicals, an ecological pool may be the best choice. Here we go through the differences so you can find the right solution for your home!`,
    image:
      '/assets/images/blog/blog-post-the-difference-between-natural-pool-and-traditional-pool.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.difference.seo.title:Faunapoolen | nature pools, bio pools, eco pools, and chemical-free pools - design and construction by experts in Sweden`,
      path: '/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      keywords: $localize`:@@blog.difference.seo.keywords:nature pool, custom pools, build nature pool, chemical-free pool, natural pool, organic pool, water landscape, sustainable pool, pool design, pool installation, garden design, pool maintenance, chemical-free water landscapes, fountains, aquascape, aquascape pools`,
      description: $localize`:@@blog.difference.seo.description:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogTitle: $localize`:@@blog.difference.seo.ogTitle:Faunapoolen`,
      ogDescription: $localize`:@@blog.difference.seo.ogDescription:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      enPath: '/en/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      daPath: '/da/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: '5-common-problems-installing-a-nature-pool',
    title: $localize`:@@blog.5-common-problems-installing-a-nature-pool.title:5 common problems with natural pools and chlorine-free pools`,
    intro: $localize`:@@blog.5-common-problems-installing-a-nature-pool.intro:Avoid the most common problems when installing a nature pool. Learn about ecosystems, placement, sealing, circulation, and plant selection for a sustainable natural pool.`,
    image: '/assets/images/blog/blog-post-5-problems-with-a-natural-pool.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.title:Nature pool problems | how to succeed with an ecological pool`,
      path: '/blog/posts/5-common-problems-installing-a-nature-pool.html',
      keywords: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.keywords:ecological pool, chlorine-free pool, eco-friendly pool, organic pool, swimming pond, nature pool problems, water landscape`,
      description: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.description:Avoid common mistakes when planning an ecological pool or chlorine-free pool: balance, placement, sealing, circulation, and the right plants.`,
      ogTitle: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.ogTitle:Common problems with nature pools`,
      ogDescription: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.ogDescription:Avoid mistakes with ecological pools and chlorine-free pools: balance, placement, sealing, and circulation.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/5-common-problems-installing-a-nature-pool-og.jpg',
      ogType: 'article',
      datePublished: '2026-04-14',
      enPath: '/en/blog/posts/5-common-problems-installing-a-nature-pool.html',
      daPath: '/da/blog/posts/5-common-problems-installing-a-nature-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams',
    title: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.title:Water management on golf courses: ponds, lakes, and streams`,
    intro: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.intro:Water is both an asset and a risk on golf courses. A well-designed pond can frame a fairway, create strategic challenges, and provide storage for irrigation.`,
    image: '/assets/images/blog/Blog-Golf-Header-Image.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.title:Water landscapes for golf courses | ponds, lakes, and streams`,
      path: '/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      keywords: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.keywords:water landscapes, pond, rainwater collection, natural garden design, water management, eco-friendly pool`,
      description: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.description:Faunapoolen helps golf clubs with water landscapes, ponds, lakes, streams, and sustainable water management for function and aesthetics.`,
      ogTitle: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.ogTitle:Water landscapes for golf courses`,
      ogDescription: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.ogDescription:Sustainable maintenance and design of ponds, lakes, streams, and water landscapes on golf courses.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams-og.jpg',
      ogType: 'article',
      datePublished: '2026-03-10',
      enPath: '/en/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      daPath: '/da/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'pool-conversions',
    title: $localize`:@@blog.pool-conversions.title:Convert chlorine pool to natural pool or swimming pond`,
    intro: $localize`:@@blog.pool-conversions.intro:The idea of transforming an existing traditional pool into a sustainable, low-maintenance, and beautiful natural swimming pond is growing in both Europe and Scandinavia.`,
    image: '/assets/images/koi-ponds/pool-pond-hero.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.pool-conversions.seo.title:Pool conversion | from chlorine pool to organic pool.`,
      path: '/blog/posts/pool-conversions.html',
      keywords: $localize`:@@blog.pool-conversions.seo.keywords:organic pool, chlorine-free pool, ecological pool, swimming pond, pool conversion, environmentally friendly pool`,
      description: $localize`:@@blog.pool-conversions.seo.description:See how a traditional pool can be converted into an organic pool, swimming pond, or ecological pool with natural filtration without chlorine.`,
      ogTitle: $localize`:@@blog.pool-conversions.seo.ogTitle:Convert pool to organic pool`,
      ogDescription: $localize`:@@blog.pool-conversions.seo.ogDescription:From chlorine pool to organic pool, swimming pond, or ecological pool with natural filtration.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/pool-conversions-og.jpg',
      ogType: 'article',
      datePublished: '2026-01-27',
      enPath: '/en/blog/posts/pool-conversions.html',
      daPath: '/da/blog/posts/pool-conversions.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'sports-stars-natural-ponds',
    title: $localize`:@@blog.sports-stars-natural-ponds.title:Swimming pond for recovery and cold baths without chlorine`,
    intro: $localize`:@@blog.sports-stars-natural-ponds.intro:In the pursuit of peak performance, elite athletes are constantly looking for ways to optimize recovery, enhance well-being, and extend their careers. One of the latest trends emerging in both Europe and the USA is found not in the gym or clinic – but in the garden. From football legends to NBA stars, natural ponds are becoming an increasingly common part of homes, featuring chemical-free water, deep recovery benefits, and year-round tranquility.`,
    image: '/assets/images/blog/sports-stars-natural-ponds.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.sports-stars-natural-ponds.seo.title:Natural pond for recovery | chlorine-free pool`,
      path: '/blog/posts/sports-stars-natural-ponds.html',
      keywords: $localize`:@@blog.sports-stars-natural-ponds.seo.keywords:natural pond, chlorine-free pool, ecological pool, organic pool, eco-friendly pool, cold bath`,
      description: $localize`:@@blog.sports-stars-natural-ponds.seo.description:That's why athletes choose natural ponds and chlorine-free pools for recovery, cold baths, and natural water at home.`,
      ogTitle: $localize`:@@blog.sports-stars-natural-ponds.seo.ogTitle:Natural pond for recovery`,
      ogDescription: $localize`:@@blog.sports-stars-natural-ponds.seo.ogDescription:Natural pond and chlorine-free pool for recovery, cold baths, and natural water at home.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/sports-stars-natural-ponds-og.jpg',
      ogType: 'article',
      datePublished: '2025-11-18',
      enPath: '/en/blog/posts/sports-stars-natural-ponds.html',
      daPath: '/da/blog/posts/sports-stars-natural-ponds.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option',
    title: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.title:Rainwater collection when a well is not an option`,
    intro: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.intro:More and more homeowners are exploring sustainable living and eco-friendly landscape architecture. But what do you do when a traditional well doesn't meet your water needs? At Faunapoolen, we understand how important it is to find smart ways to develop outdoor environments while conserving water. Water storage can be an excellent alternative if you live in an area with drilling restrictions or simply want to choose a more sustainable solution.`,
    image: '/assets/images/blog/blog-post-water-storage-solutions.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.title:Rainwater harvesting | water storage for sustainable gardens`,
      path: '/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      keywords: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.keywords:rainwater harvesting, water landscape, natural garden design, eco-friendly pool, pond, water storage`,
      description: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.description:Learn how rainwater harvesting and water storage can supply gardens, ponds, and water landscapes when traditional wells are not sufficient.`,
      ogTitle: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.ogTitle:Rainwater harvesting and water storage`,
      ogDescription: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.ogDescription:Water storage and rainwater harvesting for gardens, ponds, and sustainable water landscapes.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option-og.jpg',
      ogType: 'article',
      datePublished: '2025-10-21',
      enPath:
        '/en/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      daPath:
        '/da/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'creating-harmony-intergrating-water-features-with-your-landscape',
    title: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.title:Water landscape in the garden: waterfall, koi pond, and fountain`,
    intro: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.intro:A well-designed water feature should feel like a natural extension of the surrounding landscape. With the right placement, materials, and ecological balance, the water feature becomes the heart of the garden.`,
    image: '/assets/images/blog/blog-post-creating-harmony.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
    ],
    seo: {
      title: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.title:Water landscaping | waterfalls, koi ponds, and fountains`,
      path: '/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      keywords: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.keywords:water landscaping, waterfall garden, koi pond, fountain, natural garden design, eco-friendly pool`,
      description: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.description:How to integrate waterfalls, koi ponds, and fountains into a natural garden design with ecological balance.`,
      ogTitle: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.ogTitle:Water landscapes in the garden`,
      ogDescription: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.ogDescription:Integrate waterfalls, koi ponds, and fountains into a natural garden design.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/creating-harmony-intergrating-water-features-with-your-landscape-og.jpg',
      ogType: 'article',
      datePublished: '2025-09-30',
      enPath:
        '/en/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      daPath:
        '/da/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'small-features-for-small-spaces',
    title: $localize`:@@blog.small-features-for-small-spaces.title:Waterfall, fountain, and mini pond for small garden`,
    intro: $localize`:@@blog.small-features-for-small-spaces.intro:A compact garden does not mean you have to sacrifice the tranquility and beauty of water features. With innovative design and thoughtful placement, even the smallest spaces can accommodate an elegant pond-free waterfall, a mini-pond with koi, or a discreet bubbling fountain. In this guide, we explore how you can transform small outdoor areas into fantastic, eco-friendly oases with water features that combine aesthetics, sustainability, and practical function.`,
    image: '/assets/images/blog/small-features-for-small-spaces.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.small-features-for-small-spaces.seo.title:Waterfalls and fountains for small gardens`,
      path: '/blog/posts/small-features-for-small-spaces.html',
      keywords: $localize`:@@blog.small-features-for-small-spaces.seo.keywords:waterfall garden, fountain, koi pond, rainwater collection, natural garden design, water landscape`,
      description: $localize`:@@blog.small-features-for-small-spaces.seo.description:Small gardens can accommodate waterfalls, fountains, mini-ponds, and rainwater collection with smart natural garden design.`,
      ogTitle: $localize`:@@blog.small-features-for-small-spaces.seo.ogTitle:Waterfalls and fountains for small spaces`,
      ogDescription: $localize`:@@blog.small-features-for-small-spaces.seo.ogDescription:Waterfalls, fountains, mini-ponds, and rainwater collection for small gardens.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/small-features-for-small-spaces-og.jpg',
      ogType: 'article',
      datePublished: '2025-09-02',
      enPath: '/en/blog/posts/small-features-for-small-spaces.html',
      daPath: '/da/blog/posts/small-features-for-small-spaces.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'algae-control-and-maintenance-tips',
    title: $localize`:@@blog.algae-control-and-maintenance-tips.title:Algae in pond? Maintenance of koi ponds and water landscapes`,
    intro: $localize`:@@blog.algae-control-and-maintenance-tips.intro:Here you will find concrete advice to reduce algae in ponds, koi ponds, and water landscapes without disturbing the biological balance.`,
    image: '/assets/images/blog/blog-post-how-to-manage-algie.jpg',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.algae-control-and-maintenance-tips.seo.title:Algae control | maintenance of koi ponds and water landscapes`,
      path: '/blog/posts/algae-control-and-maintenance-tips.html',
      keywords: $localize`:@@blog.algae-control-and-maintenance-tips.seo.keywords:koi pond, water landscape, garden maintenance, fountain, algae control, biological filtration, natural garden design`,
      description: $localize`:@@blog.algae-control-and-maintenance-tips.seo.description:Get advice on algae control, biological balance, and garden maintenance for koi ponds, fountains, and sustainable water landscapes.`,
      ogTitle: $localize`:@@blog.algae-control-and-maintenance-tips.seo.ogTitle:Algae control and garden maintenance`,
      ogDescription: $localize`:@@blog.algae-control-and-maintenance-tips.seo.ogDescription:Advice on algae control, biological balance, and maintenance for koi ponds, fountains, and water landscapes.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/algae-control-and-maintenance-tips-og.jpg',
      ogType: 'article',
      datePublished: '2025-08-05',
      enPath: '/en/blog/posts/algae-control-and-maintenance-tips.html',
      daPath: '/da/blog/posts/algae-control-and-maintenance-tips.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'how-filtering-works-with-nature-pools',
    title: $localize`:@@blog.how-filtering-works-with-nature-pools.title:Biological filtration in natural pools: how to purify chlorine-free pools`,
    intro: $localize`:@@blog.how-filtering-works-with-nature-pools.intro:Nature pools are a beautiful and sustainable alternative to traditional swimming pools. One of the most fascinating aspects of nature pools is their unique water filtration system, which uses nature itself to keep the water clean and safe for swimming.`,
    image: '/assets/images/blog/blog-post-how-water-is-filtered.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.title:How an ecological pool is filtered without chlorine`,
      path: '/blog/posts/how-filtering-works-with-nature-pools.html',
      keywords: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.keywords:ecological pool, chlorine-free pool, swimming pond, organic pool, biological filtration, environmentally friendly pool`,
      description: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.description:Understand how biological filtration purifies an ecological pool, swimming pond, or organic pool without chlorine and strong chemicals.`,
      ogTitle: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.ogTitle:Filtration in ecological pool`,
      ogDescription: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.ogDescription:This is how ecological pools, swimming ponds, and organic pools are purified with biological filtration without chlorine.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/how-filtering-works-with-nature-pools-og.jpg',
      ogType: 'article',
      datePublished: '2025-07-08',
      enPath: '/en/blog/posts/how-filtering-works-with-nature-pools.html',
      daPath: '/da/blog/posts/how-filtering-works-with-nature-pools.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'why-you-should-get-a-natural-pool',
    title: $localize`:@@blog.why-you-should-get-a-natural-pool.title:Why choose an ecological pool without chlorine?`,
    intro: $localize`:@@blog.why-you-should-get-a-natural-pool.intro:Natural pools have increased in popularity in recent years and offer a sustainable and environmentally friendly alternative to traditional chlorine pools. Whether you want to reduce your environmental impact or simply love the idea of a chemical-free swimming experience, a natural pool offers many benefits. Here’s why you should consider investing in one for your home.`,
    image: '/assets/images/blog/blog-post-why-you-should-have-a-natural-pool.webp',
    related: [
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
    ],
    seo: {
      title: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.title:Why choose an ecological pool and chlorine-free pool`,
      path: '/blog/posts/why-you-should-get-a-natural-pool.html',
      keywords: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.keywords:ecological pool, chlorine-free pool, environmentally friendly pool, organic pool, swimming pond, natural garden design`,
      description: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.description:An ecological pool provides swimming without chlorine, low chemical use, natural design, and an environmentally friendly pool that blends into the garden.`,
      ogTitle: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.ogTitle:Why choose an ecological pool`,
      ogDescription: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.ogDescription:Swimming without chlorine, low chemical use, and natural design with an environmentally friendly pool.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/why-you-should-get-a-natural-pool-og.jpg',
      ogType: 'article',
      datePublished: '2025-06-12',
      enPath: '/en/blog/posts/why-you-should-get-a-natural-pool.html',
      daPath: '/da/blog/posts/why-you-should-get-a-natural-pool.html',
      defaultLanguage: 'sv',
    },
  },
];
