import type { FaunapoolenGuideId } from './faunapoolen-content';
import type { PageSeo } from '../../shared/seo';
export interface BlogArticle {
  readonly id: FaunapoolenGuideId;
  readonly title: string;
  readonly intro: string;
  readonly image: string;
  readonly related: readonly FaunapoolenGuideId[];
  readonly seo: PageSeo & { title: string };
}
export const BLOG_ARTICLES: readonly BlogArticle[] = [
  {
    id: 'naturpool-i-sodra-sverige',
    title: $localize`:@@blog.naturpool-i-sodra-sverige.title:Nature pools in southern Sweden: planning your garden`,
    intro: $localize`:@@blog.naturpool-i-sodra-sverige.intro:Planning a nature pool in Skåne, Halland, Blekinge or Småland? Start with how you want to swim, the space around your home and a realistic budget. Here is what to consider when commissioning a pool designed for your garden.`,
    image: '/assets/images/faunapoolen/gotland/1455.webp',
    related: [
      'hur-mycket-plats-behover-en-naturpool',
      'naturpool-fran-forsta-samtal-till-bad',
      'vad-kostar-det-att-aga-en-naturpool',
      'how-filtering-works-with-nature-pools',
      'skotsel-av-naturpool-under-aret',
      'why-you-should-get-a-natural-pool',
    ],
    seo: {
      title: $localize`:@@blog.naturpool-i-sodra-sverige.seo.title:Nature pools in southern Sweden – Skåne, Halland, Blekinge & Småland | Faunapoolen`,
      description: $localize`:@@blog.naturpool-i-sodra-sverige.seo.description:Planning a nature pool in southern Sweden? Explore space, design, budget and installation with Faunapoolen in Skåne, Halland, Blekinge and Småland.`,
      path: '/blog/posts/naturpool-i-sodra-sverige.html',
      enPath: '/en/blog/posts/naturpool-i-sodra-sverige.html',
      daPath: '/da/blog/posts/naturpool-i-sodra-sverige.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/faunapoolen/gotland/1455.webp',
      ogType: 'article',
      datePublished: '2026-09-30',
      dateModified: '2026-09-30',
    },
  },
  {
    id: 'build',
    title: $localize`:@@blog.build.title:Building a nature pool – how to do it yourself`,
    intro: $localize`:@@blog.build.intro:Building a nature pool yourself is a dream for many who want to create a unique, eco-friendly, and harmonious place in their garden. A nature pool not only offers a swimming experience free from chemicals but also becomes an aesthetic part of the garden that blends into nature. Constructing a nature pool can seem like a big challenge, but it is possible with the right planning and knowledge. In this guide, you will learn how to do it, what risks exist, and how to avoid common mistakes.`,
    image: '/assets/images/blog/blog-post-mood-image-1.jpg',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'difference',
      'pool-conversions',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'naturpool-fran-forsta-samtal-till-bad',
    ],
    seo: {
      title: $localize`:@@blog.build.seo.title:Faunapoolen | nature pools, bio pools, eco pools, and chemical-free pools - design and construction by experts in Sweden`,
      path: '/blog/posts/build-your-own-nature-pool.html',
      keywords: $localize`:@@blog.build.seo.keywords:nature pool, custom pools, build nature pool, chemical-free pool, natural pool, organic pool, water landscape, sustainable pool, pool design, pool installation, garden design, pool maintenance, chemical-free water landscapes, fountains, aquascape, aquascape pools`,
      description: $localize`:@@blog.build.seo.description:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogTitle: $localize`:@@blog.build.seo.ogTitle:Faunapoolen`,
      ogDescription: $localize`:@@blog.build.seo.ogDescription:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      enPath: '/en/blog/posts/build-your-own-nature-pool.html',
      daPath: '/da/blog/posts/build-your-own-nature-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'difference',
    title: $localize`:@@blog.difference.title:Difference between a natural pool and a regular pool – which one should you choose?`,
    intro: $localize`:@@blog.difference.intro:Having a pool at home is a dream for many. It transforms the garden into a place for relaxation, fun, and refreshing dips on hot summer days. But when choosing a pool, there is an important question to ask: should you build a natural pool or a traditional pool? Both options have their advantages, but if you want a sustainable pool without chemicals, an ecological pool may be the best choice. Here we go through the differences so you can find the right solution for your home!`,
    image:
      '/assets/images/blog/blog-post-the-difference-between-natural-pool-and-traditional-pool.webp',
    related: [
      'why-you-should-get-a-natural-pool',
      '5-common-problems-installing-a-nature-pool',
      'pool-conversions',
      'build',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'naturpool-fran-forsta-samtal-till-bad',
    ],
    seo: {
      title: $localize`:@@blog.difference.seo.title:Faunapoolen | nature pools, bio pools, eco pools, and chemical-free pools - design and construction by experts in Sweden`,
      path: '/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      keywords: $localize`:@@blog.difference.seo.keywords:nature pool, custom pools, build nature pool, chemical-free pool, natural pool, organic pool, water landscape, sustainable pool, pool design, pool installation, garden design, pool maintenance, chemical-free water landscapes, fountains, aquascape, aquascape pools`,
      description: $localize`:@@blog.difference.seo.description:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogTitle: $localize`:@@blog.difference.seo.ogTitle:Faunapoolen`,
      ogDescription: $localize`:@@blog.difference.seo.ogDescription:We design and build nature pools, bio pools, eco pools, chemical-free pools, and swimming ponds.`,
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      enPath: '/en/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      daPath: '/da/blog/posts/difference-between-normal-pool-and-natural-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: '5-common-problems-installing-a-nature-pool',
    title: $localize`:@@blog.5-common-problems-installing-a-nature-pool.title:5 nature-pool problems to prevent during planning`,
    intro: $localize`:@@blog.5-common-problems-installing-a-nature-pool.intro:A successful nature pool starts with the site, the way you want to swim and a system designed for both. These five questions help you judge a proposal before construction begins.`,
    image: '/assets/images/blog/blog-post-5-problems-with-a-natural-pool.webp',
    related: [
      'how-filtering-works-with-nature-pools',
      'algae-control-and-maintenance-tips',
      'build',
      'hur-mycket-plats-behover-en-naturpool',
      'naturpool-sakerhet-och-tillstand',
      'naturpool-fran-forsta-samtal-till-bad',
    ],
    seo: {
      title: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.title:Nature-pool problems: 5 planning risks | Faunapoolen`,
      path: '/blog/posts/5-common-problems-installing-a-nature-pool.html',
      keywords: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.keywords:nature pool problems, natural pool planning, swimming pond`,
      description: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.description:Position, sealing, circulation, filtration and planting affect a nature pool. Learn what needs assessing before construction starts.`,
      ogTitle: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.ogTitle:5 nature-pool problems to prevent during planning`,
      ogDescription: $localize`:@@blog.5-common-problems-installing-a-nature-pool.seo.ogDescription:Position, sealing, circulation, filtration and planting affect a nature pool. Learn what needs assessing before construction starts.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/5-common-problems-installing-a-nature-pool-og.jpg',
      ogType: 'article',
      datePublished: '2026-04-14',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/5-common-problems-installing-a-nature-pool.html',
      daPath: '/da/blog/posts/5-common-problems-installing-a-nature-pool.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams',
    title: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.title:Plan the care of golf-course ponds and streams`,
    intro: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.intro:A clear inventory makes water management easier to discuss. Define what each pond does, document how water moves and plan care around the course’s actual needs.`,
    image: '/assets/images/blog/Blog-Golf-Header-Image.webp',
    related: [
      'algae-control-and-maintenance-tips',
      'can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'small-features-for-small-spaces',
      'how-filtering-works-with-nature-pools',
      'skotsel-av-naturpool-under-aret',
    ],
    seo: {
      title: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.title:Golf-course ponds: planning and maintenance | Faunapoolen`,
      path: '/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      keywords: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.keywords:golf course pond, golf course water management, pond maintenance golf, golf course stream`,
      description: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.description:Ponds and streams need to work for the course and its maintenance team. Read about inventories, water flow and questions for an initial assessment.`,
      ogTitle: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.ogTitle:Plan the care of golf-course ponds and streams`,
      ogDescription: $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.seo.ogDescription:Ponds and streams need to work for the course and its maintenance team. Read about inventories, water flow and questions for an initial assessment.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams-og.jpg',
      ogType: 'article',
      datePublished: '2026-03-10',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      daPath: '/da/blog/posts/how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'pool-conversions',
    title: $localize`:@@blog.pool-conversions.title:Can your existing pool become a nature pool?`,
    intro: $localize`:@@blog.pool-conversions.intro:An existing pool can be a starting point, but its structure, available space and new cleaning system need to work together. Here is what to investigate before deciding on conversion.`,
    image: '/assets/images/koi-ponds/pool-pond-hero.webp',
    related: [
      'how-filtering-works-with-nature-pools',
      'difference',
      'naturpool-fran-forsta-samtal-till-bad',
      '5-common-problems-installing-a-nature-pool',
      'hur-mycket-plats-behover-en-naturpool',
      'vad-kostar-det-att-aga-en-naturpool',
    ],
    seo: {
      title: $localize`:@@blog.pool-conversions.seo.title:Convert a pool to a nature pool: what needs assessing? | Faunapoolen`,
      path: '/blog/posts/pool-conversions.html',
      keywords: $localize`:@@blog.pool-conversions.seo.keywords:pool conversion, convert pool to natural pool, existing pool, biological filtration`,
      description: $localize`:@@blog.pool-conversions.seo.description:The pool structure, cleaning system and surrounding space determine whether conversion is possible. Explore what needs assessing before you proceed.`,
      ogTitle: $localize`:@@blog.pool-conversions.seo.ogTitle:Can your existing pool become a nature pool?`,
      ogDescription: $localize`:@@blog.pool-conversions.seo.ogDescription:The pool structure, cleaning system and surrounding space determine whether conversion is possible. Explore what needs assessing before you proceed.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/pool-conversions-og.jpg',
      ogType: 'article',
      datePublished: '2026-01-27',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/pool-conversions.html',
      daPath: '/da/blog/posts/pool-conversions.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'sports-stars-natural-ponds',
    title: $localize`:@@blog.sports-stars-natural-ponds.title:Cold bathing in a nature pool: plan your bathing place`,
    intro: $localize`:@@blog.sports-stars-natural-ponds.intro:If cold bathing is part of your plans, the route to the water and the system’s winter operation matter as much as its appearance. Start with how you want to use the place.`,
    image: '/assets/images/blog/sports-stars-natural-ponds.webp',
    related: [
      'skotsel-av-naturpool-under-aret',
      'naturpool-sakerhet-och-tillstand',
      'why-you-should-get-a-natural-pool',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'how-filtering-works-with-nature-pools',
      'vad-kostar-det-att-aga-en-naturpool',
    ],
    seo: {
      title: $localize`:@@blog.sports-stars-natural-ponds.seo.title:Cold bathing in a nature pool: plan for home | Faunapoolen`,
      path: '/blog/posts/sports-stars-natural-ponds.html',
      keywords: $localize`:@@blog.sports-stars-natural-ponds.seo.keywords:cold bathing nature pool, natural pool sauna, garden plunge pool, winter operation`,
      description: $localize`:@@blog.sports-stars-natural-ponds.seo.description:Considering cold bathing at home? Explore location, access to the water and winter-operation questions when planning a nature pool.`,
      ogTitle: $localize`:@@blog.sports-stars-natural-ponds.seo.ogTitle:Cold bathing in a nature pool: plan your bathing place`,
      ogDescription: $localize`:@@blog.sports-stars-natural-ponds.seo.ogDescription:Considering cold bathing at home? Explore location, access to the water and winter-operation questions when planning a nature pool.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/sports-stars-natural-ponds-og.jpg',
      ogType: 'article',
      datePublished: '2025-11-18',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/sports-stars-natural-ponds.html',
      daPath: '/da/blog/posts/sports-stars-natural-ponds.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option',
    title: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.title:Collecting rainwater when a well is not an option`,
    intro: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.intro:Rainwater storage can supplement water for the garden. Its usefulness depends on what you collect, what you need and how much you can store between periods of rain.`,
    image: '/assets/images/blog/blog-post-water-storage-solutions.webp',
    related: [
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'how-filtering-works-with-nature-pools',
      'small-features-for-small-spaces',
      'how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams',
      'algae-control-and-maintenance-tips',
      'skotsel-av-naturpool-under-aret',
    ],
    seo: {
      title: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.title:Store rainwater for the garden and pond | Faunapoolen`,
      path: '/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      keywords: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.keywords:rainwater collection garden, store rainwater, rainwater pond, garden water storage`,
      description: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.description:Roof area, water demand and storage space determine the value of rainwater collection. Explore what to plan for a garden or pond.`,
      ogTitle: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.ogTitle:Collecting rainwater when a well is not an option`,
      ogDescription: $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.seo.ogDescription:Roof area, water demand and storage space determine the value of rainwater collection. Explore what to plan for a garden or pond.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option-og.jpg',
      ogType: 'article',
      datePublished: '2025-10-21',
      dateModified: '2026-09-17',
      enPath:
        '/en/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      daPath:
        '/da/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'creating-harmony-intergrating-water-features-with-your-landscape',
    title: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.title:Plan a nature pool and water features as part of your garden`,
    intro: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.intro:A good water landscape connects the places where you swim, sit and move through the garden. Begin with those everyday moments, then choose the water, materials and planting.`,
    image: '/assets/images/blog/blog-post-creating-harmony.webp',
    related: [
      'small-features-for-small-spaces',
      'hur-mycket-plats-behover-en-naturpool',
      'why-you-should-get-a-natural-pool',
      'difference',
      'naturpool-fran-forsta-samtal-till-bad',
      'can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option',
    ],
    seo: {
      title: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.title:Plan a nature pool and garden water features | Faunapoolen`,
      path: '/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      keywords: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.keywords:nature pool garden design, water features garden, pond landscape, garden waterfall`,
      description: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.description:Plan swimming space, paths, seating, planting and waterfalls together. Explore the choices that make a garden water feature useful every day.`,
      ogTitle: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.ogTitle:Plan a nature pool and water features as part of your garden`,
      ogDescription: $localize`:@@blog.creating-harmony-intergrating-water-features-with-your-landscape.seo.ogDescription:Plan swimming space, paths, seating, planting and waterfalls together. Explore the choices that make a garden water feature useful every day.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/creating-harmony-intergrating-water-features-with-your-landscape-og.jpg',
      ogType: 'article',
      datePublished: '2025-09-30',
      dateModified: '2026-09-17',
      enPath:
        '/en/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      daPath:
        '/da/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'small-features-for-small-spaces',
    title: $localize`:@@blog.small-features-for-small-spaces.title:A fountain, small pond or waterfall for a small garden?`,
    intro: $localize`:@@blog.small-features-for-small-spaces.intro:You do not need a swimming area to enjoy water in the garden. Compare a fountain, a waterfall with a hidden reservoir and a small planted pond, including the space their care needs.`,
    image: '/assets/images/blog/small-features-for-small-spaces.webp',
    related: [
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'hur-mycket-plats-behover-en-naturpool',
      'algae-control-and-maintenance-tips',
      'can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option',
      'how-filtering-works-with-nature-pools',
      'why-you-should-get-a-natural-pool',
    ],
    seo: {
      title: $localize`:@@blog.small-features-for-small-spaces.seo.title:Water in a small garden: fountain, pond or waterfall | Faunapoolen`,
      path: '/blog/posts/small-features-for-small-spaces.html',
      keywords: $localize`:@@blog.small-features-for-small-spaces.seo.keywords:water small garden, small garden fountain, pondless waterfall, small garden pond`,
      description: $localize`:@@blog.small-features-for-small-spaces.seo.description:Compare a fountain, pondless waterfall and small pond for a compact garden. Explore location, sound and the care each option needs.`,
      ogTitle: $localize`:@@blog.small-features-for-small-spaces.seo.ogTitle:A fountain, small pond or waterfall for a small garden?`,
      ogDescription: $localize`:@@blog.small-features-for-small-spaces.seo.ogDescription:Compare a fountain, pondless waterfall and small pond for a compact garden. Explore location, sound and the care each option needs.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/small-features-for-small-spaces-og.jpg',
      ogType: 'article',
      datePublished: '2025-09-02',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/small-features-for-small-spaces.html',
      daPath: '/da/blog/posts/small-features-for-small-spaces.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'algae-control-and-maintenance-tips',
    title: $localize`:@@blog.algae-control-and-maintenance-tips.title:Algae in a nature pool or pond: what should you check?`,
    intro: $localize`:@@blog.algae-control-and-maintenance-tips.intro:Start by finding out what has changed. The appearance of the algae, recent weather and the way your system is running give more useful clues than choosing a treatment at random.`,
    image: '/assets/images/blog/blog-post-how-to-manage-algie.jpg',
    related: [
      'how-filtering-works-with-nature-pools',
      'skotsel-av-naturpool-under-aret',
      '5-common-problems-installing-a-nature-pool',
      'vad-kostar-det-att-aga-en-naturpool',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams',
    ],
    seo: {
      title: $localize`:@@blog.algae-control-and-maintenance-tips.seo.title:Algae in nature pools and ponds: causes and checks | Faunapoolen`,
      path: '/blog/posts/algae-control-and-maintenance-tips.html',
      keywords: $localize`:@@blog.algae-control-and-maintenance-tips.seo.keywords:algae nature pool, green pond water, pond maintenance`,
      description: $localize`:@@blog.algae-control-and-maintenance-tips.seo.description:Green water or string algae? Learn what to check about nutrients, circulation and care, and when the water needs a closer assessment.`,
      ogTitle: $localize`:@@blog.algae-control-and-maintenance-tips.seo.ogTitle:Algae in a nature pool or pond: what should you check?`,
      ogDescription: $localize`:@@blog.algae-control-and-maintenance-tips.seo.ogDescription:Green water or string algae? Learn what to check about nutrients, circulation and care, and when the water needs a closer assessment.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/algae-control-and-maintenance-tips-og.jpg',
      ogType: 'article',
      datePublished: '2025-08-05',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/algae-control-and-maintenance-tips.html',
      daPath: '/da/blog/posts/algae-control-and-maintenance-tips.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'how-filtering-works-with-nature-pools',
    title: $localize`:@@blog.how-filtering-works-with-nature-pools.title:How water is cleaned in a nature pool`,
    intro: $localize`:@@blog.how-filtering-works-with-nature-pools.intro:Biological treatment is a system, not a plant added to an ordinary pool. Debris collection, filter surfaces and circulation need to work together, with care suited to the installation.`,
    image: '/assets/images/blog/blog-post-how-water-is-filtered.webp',
    related: [
      '5-common-problems-installing-a-nature-pool',
      'algae-control-and-maintenance-tips',
      'why-you-should-get-a-natural-pool',
      'skotsel-av-naturpool-under-aret',
      'difference',
      'vad-kostar-det-att-aga-en-naturpool',
    ],
    seo: {
      title: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.title:How nature-pool filtration works | Faunapoolen`,
      path: '/blog/posts/how-filtering-works-with-nature-pools.html',
      keywords: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.keywords:nature pool filtration, biological filtration, natural swimming pool`,
      description: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.description:Follow the water through a nature pool: debris collection, biological filtration and circulation, with the care each part needs.`,
      ogTitle: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.ogTitle:How water is cleaned in a nature pool`,
      ogDescription: $localize`:@@blog.how-filtering-works-with-nature-pools.seo.ogDescription:Follow the water through a nature pool: debris collection, biological filtration and circulation, with the care each part needs.`,
      ogImage:
        'https://faunapoolen.se/assets/images/og/how-filtering-works-with-nature-pools-og.jpg',
      ogType: 'article',
      datePublished: '2025-07-08',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/how-filtering-works-with-nature-pools.html',
      daPath: '/da/blog/posts/how-filtering-works-with-nature-pools.html',
      defaultLanguage: 'sv',
    },
  },
  {
    id: 'why-you-should-get-a-natural-pool',
    title: $localize`:@@blog.why-you-should-get-a-natural-pool.title:Life with a nature pool: swimming, garden and care`,
    intro: $localize`:@@blog.why-you-should-get-a-natural-pool.intro:A morning dip, a seat beside the water or an afternoon together: a nature pool can give the garden a new purpose. Decide how you want to use it, then consider the space, budget and care that go with it.`,
    image: '/assets/images/blog/blog-post-why-you-should-have-a-natural-pool.webp',
    related: [
      'difference',
      'skotsel-av-naturpool-under-aret',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'hur-mycket-plats-behover-en-naturpool',
      'naturpool-fran-forsta-samtal-till-bad',
      'vad-kostar-det-att-aga-en-naturpool',
    ],
    seo: {
      title: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.title:Life with a nature pool: swimming, garden and care | Faunapoolen`,
      path: '/blog/posts/why-you-should-get-a-natural-pool.html',
      keywords: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.keywords:nature pool benefits, nature pool garden, life with a natural pool`,
      description: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.description:Morning swims and time beside the water: explore everyday life with a nature pool and the space, budget and care it needs.`,
      ogTitle: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.ogTitle:Life with a nature pool: swimming, garden and care`,
      ogDescription: $localize`:@@blog.why-you-should-get-a-natural-pool.seo.ogDescription:Morning swims and time beside the water: explore everyday life with a nature pool and the space, budget and care it needs.`,
      ogImage: 'https://faunapoolen.se/assets/images/og/why-you-should-get-a-natural-pool-og.jpg',
      ogType: 'article',
      datePublished: '2025-06-12',
      dateModified: '2026-09-17',
      enPath: '/en/blog/posts/why-you-should-get-a-natural-pool.html',
      daPath: '/da/blog/posts/why-you-should-get-a-natural-pool.html',
      defaultLanguage: 'sv',
    },
  },

  {
    id: 'hur-mycket-plats-behover-en-naturpool',
    title: $localize`:@@blog.hur-mycket-plats-behover-en-naturpool.title:How much space does a natural pool need?`,
    intro: $localize`:@@blog.hur-mycket-plats-behover-en-naturpool.intro:The swimming area is only part of a natural pool. Treatment, edges, paths and maintenance access all need a place in the garden. Start with how you want to use the water, then assess the whole installation.`,
    image: '/assets/images/faunapoolen/gotland/1423.webp',
    related: [
      '5-common-problems-installing-a-nature-pool',
      'small-features-for-small-spaces',
      'naturpool-fran-forsta-samtal-till-bad',
      'difference',
      'creating-harmony-intergrating-water-features-with-your-landscape',
      'naturpool-sakerhet-och-tillstand',
    ],
    seo: {
      title: $localize`:@@blog.hur-mycket-plats-behover-en-naturpool.seo.title:How much space does a natural pool need? | Faunapoolen`,
      description: $localize`:@@blog.hur-mycket-plats-behover-en-naturpool.seo.description:Find out how swimming space, filtration, edges and access affect whether a natural pool fits your garden, and what to prepare for a site assessment.`,
      path: '/blog/posts/hur-mycket-plats-behover-en-naturpool.html',
      enPath: '/en/blog/posts/hur-mycket-plats-behover-en-naturpool.html',
      daPath: '/da/blog/posts/hur-mycket-plats-behover-en-naturpool.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      ogType: 'article',
      datePublished: '2026-09-17',
      dateModified: '2026-09-17',
    },
  },
  {
    id: 'skotsel-av-naturpool-under-aret',
    title: $localize`:@@blog.skotsel-av-naturpool-under-aret.title:Natural pool care through the four seasons`,
    intro: $localize`:@@blog.skotsel-av-naturpool-under-aret.intro:A natural pool needs regular attention to leaves, water level, circulation and its surroundings. Use the seasons to organize that work, with the handover plan and equipment instructions deciding exactly what your pool needs.`,
    image: '/assets/images/faunapoolen/gotland/1496.webp',
    related: [
      'algae-control-and-maintenance-tips',
      'how-filtering-works-with-nature-pools',
      'vad-kostar-det-att-aga-en-naturpool',
      '5-common-problems-installing-a-nature-pool',
      'naturpool-sakerhet-och-tillstand',
      'naturpool-fran-forsta-samtal-till-bad',
    ],
    seo: {
      title: $localize`:@@blog.skotsel-av-naturpool-under-aret.seo.title:Natural pool care through the four seasons | Faunapoolen`,
      description: $localize`:@@blog.skotsel-av-naturpool-under-aret.seo.description:Plan natural pool care through spring, summer, autumn and winter, including leaves, water level, circulation and instructions for your installed system.`,
      path: '/blog/posts/skotsel-av-naturpool-under-aret.html',
      enPath: '/en/blog/posts/skotsel-av-naturpool-under-aret.html',
      daPath: '/da/blog/posts/skotsel-av-naturpool-under-aret.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      ogType: 'article',
      datePublished: '2026-09-17',
      dateModified: '2026-09-17',
    },
  },
  {
    id: 'naturpool-fran-forsta-samtal-till-bad',
    title: $localize`:@@blog.naturpool-fran-forsta-samtal-till-bad.title:From the first conversation to your natural pool`,
    intro: $localize`:@@blog.naturpool-fran-forsta-samtal-till-bad.intro:A commissioned natural pool starts with how you want to use your garden. Here is how the first conversation, site assessment, proposal, construction and handover fit together, and which decisions need to be made along the way.`,
    image: '/assets/images/faunapoolen/gotland/1455.webp',
    related: [
      'hur-mycket-plats-behover-en-naturpool',
      'naturpool-sakerhet-och-tillstand',
      'skotsel-av-naturpool-under-aret',
      'vad-kostar-det-att-aga-en-naturpool',
      'why-you-should-get-a-natural-pool',
      'difference',
    ],
    seo: {
      title: $localize`:@@blog.naturpool-fran-forsta-samtal-till-bad.seo.title:From the first conversation to your natural pool | Faunapoolen`,
      description: $localize`:@@blog.naturpool-fran-forsta-samtal-till-bad.seo.description:From the first conversation and site assessment to design, quotation, construction and a care plan. Understand the decisions behind a commissioned natural pool.`,
      path: '/blog/posts/naturpool-fran-forsta-samtal-till-bad.html',
      enPath: '/en/blog/posts/naturpool-fran-forsta-samtal-till-bad.html',
      daPath: '/da/blog/posts/naturpool-fran-forsta-samtal-till-bad.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      ogType: 'article',
      datePublished: '2026-09-17',
      dateModified: '2026-09-17',
    },
  },
  {
    id: 'naturpool-sakerhet-och-tillstand',
    title: $localize`:@@blog.naturpool-sakerhet-och-tillstand.title:Natural pool safety and permissions to check in Sweden`,
    intro: $localize`:@@blog.naturpool-sakerhet-och-tillstand.intro:Plan the water, protection and surrounding works together. Before building a natural pool in Sweden, establish which permissions, electrical work and water arrangements apply to the actual property and design.`,
    image: '/assets/images/faunapoolen/gotland/1437.webp',
    related: [
      'hur-mycket-plats-behover-en-naturpool',
      'naturpool-fran-forsta-samtal-till-bad',
      '5-common-problems-installing-a-nature-pool',
      'skotsel-av-naturpool-under-aret',
      'how-filtering-works-with-nature-pools',
      'vad-kostar-det-att-aga-en-naturpool',
    ],
    seo: {
      title: $localize`:@@blog.naturpool-sakerhet-och-tillstand.seo.title:Natural pool safety and permissions to check in Sweden | Faunapoolen`,
      description: $localize`:@@blog.naturpool-sakerhet-och-tillstand.seo.description:What should you ask the municipality before building a natural pool in Sweden? Check the design, child protection, electrical work and water arrangements.`,
      path: '/blog/posts/naturpool-sakerhet-och-tillstand.html',
      enPath: '/en/blog/posts/naturpool-sakerhet-och-tillstand.html',
      daPath: '/da/blog/posts/naturpool-sakerhet-och-tillstand.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      ogType: 'article',
      datePublished: '2026-09-17',
      dateModified: '2026-09-17',
    },
  },
  {
    id: 'vad-kostar-det-att-aga-en-naturpool',
    title: $localize`:@@blog.vad-kostar-det-att-aga-en-naturpool.title:What does it cost to own a natural pool?`,
    intro: $localize`:@@blog.vad-kostar-det-att-aga-en-naturpool.intro:The installation price is the beginning of the budget. Electricity, water, routine care and eventual repairs shape the cost of ownership. Here is how to estimate those items without relying on a promised annual figure.`,
    image: '/assets/images/faunapoolen/gotland/1525.webp',
    related: [
      'skotsel-av-naturpool-under-aret',
      'how-filtering-works-with-nature-pools',
      'naturpool-fran-forsta-samtal-till-bad',
      'pool-conversions',
      'difference',
      '5-common-problems-installing-a-nature-pool',
    ],
    seo: {
      title: $localize`:@@blog.vad-kostar-det-att-aga-en-naturpool.seo.title:What does it cost to own a natural pool? | Faunapoolen`,
      description: $localize`:@@blog.vad-kostar-det-att-aga-en-naturpool.seo.description:Estimate natural pool running costs with a transparent electricity example and a checklist for water, care, service and future component replacement.`,
      path: '/blog/posts/vad-kostar-det-att-aga-en-naturpool.html',
      enPath: '/en/blog/posts/vad-kostar-det-att-aga-en-naturpool.html',
      daPath: '/da/blog/posts/vad-kostar-det-att-aga-en-naturpool.html',
      defaultLanguage: 'sv',
      ogImage: 'https://faunapoolen.se/assets/images/og-image.png',
      ogType: 'article',
      datePublished: '2026-09-17',
      dateModified: '2026-09-17',
    },
  },
];
