export const FAUNAPOOLEN_COMMERCIAL = {
  definitionTitle: $localize`:@@site.commercial.definitionTitle:A place to swim, part of your garden`,
  definitionBody: $localize`:@@site.commercial.definitionBody:A nature pool combines a swimming area with biological filtration. You may also encounter the terms swimming pond, biopool or ecological pool; the names do not tell you exactly how a system works. We plan the swimming area, filtration and surroundings together, for your property.`,
  spaceGuideLink: $localize`:@@site.commercial.spaceGuideLink:How much space does a nature pool need?`,
  processGuideLink: $localize`:@@site.commercial.processGuideLink:Read about the steps from first call to swimming`,
  filterLink: $localize`:@@site.commercial.filterLink:How biological filtration works`,
  seasonalCareLink: $localize`:@@site.commercial.seasonalCareLink:Read about care through the year`,
  ownershipGuideLink: $localize`:@@site.commercial.ownershipGuideLink:What affects the running cost?`,
  careLink: $localize`:@@site.commercial.careLink:Read about algae and maintenance`,
  poolLink: $localize`:@@site.commercial.poolLink:Explore our nature pools`,
  packageLink: $localize`:@@site.commercial.packageLink:Find a pool package for your garden`,
  projectBridgeTitle: $localize`:@@site.commercial.projectBridgeTitle:What would your own swimming spot look like?`,
  projectBridgeBody: $localize`:@@site.commercial.projectBridgeBody:Explore how a nature pool works, from keeping the water clear to shaping a swimming area that feels part of your garden.`,
  caseStoryTitle: $localize`:@@site.commercial.caseStoryTitle:A swimming spot beside the house`,
  caseStoryBody: $localize`:@@site.commercial.caseStoryBody:We built this nature pool beside Brita’s home on southern Gotland. The photographs show the pool, its stone edges and the surrounding garden. Brita describes both the build and the time she and her grandchildren have spent in the water.`,
  swimmingTitle: $localize`:@@site.commercial.swimmingTitle:Would you like to swim, too?`,
  swimmingBody: $localize`:@@site.commercial.swimmingBody:A pond or stream gives you a place to spend time beside the water. If swimming is part of your plan, explore a nature pool with a swimming area and filtration designed for that purpose.`,
  gardenGuideLink: $localize`:@@site.commercial.gardenGuideLink:Plan water features with your garden`,
  waterscapeArea: $localize`:@@site.commercial.waterscapeArea:We design water features throughout Sweden and in Denmark. Tell us about your garden and we will discuss the right scope; ponds and streams are quoted individually.`,
  areaTitle: $localize`:@@site.commercial.areaTitle:Nature pools in southern Sweden`,
  areaBody: $localize`:@@site.commercial.areaBody:We build nature pools throughout Sweden and in Denmark. Here you can explore local planning questions for Skåne, Halland, Blekinge and Småland. Wherever your property is, start by telling us about the place and your ideas.`,
  pricingTitle: $localize`:@@site.commercial.pricingTitle:What does a nature pool cost?`,
  pricingIntro: $localize`:@@site.commercial.pricingIntro:Choose a starting point for your garden. We’ll help you understand what your site needs and agree a clear scope before you decide.`,
  scopeTitle: $localize`:@@site.commercial.scopeTitle:What does your pool package cover?`,
  scopeBody: $localize`:@@site.commercial.scopeBody:Your quotation sets out the work and materials for your pool, from groundwork and filtration to edges and planting. We agree any additional features and garden work with you before construction.`,
  scopeDetail: $localize`:@@site.commercial.scopeDetail:We clarify access, excavation, soil removal, electrical work, water filling and transport before you accept. You can see what is included before committing.`,
  costTitle: $localize`:@@site.commercial.costTitle:What shapes your quotation?`,
  groundTitle: $localize`:@@site.commercial.groundTitle:Ground and access`,
  groundBody: $localize`:@@site.commercial.groundBody:We assess the ground, levels and access for machinery so your quotation reflects the work your garden needs.`,
  sizeTitle: $localize`:@@site.commercial.sizeTitle:Swimming area and filtration`,
  sizeBody: $localize`:@@site.commercial.sizeBody:Your swimming area and filtration are planned together. The space you need and the way you want to swim guide the design.`,
  surroundingsTitle: $localize`:@@site.commercial.surroundingsTitle:Materials and the surrounding garden`,
  surroundingsBody: $localize`:@@site.commercial.surroundingsBody:Choose the edges, planting and places to sit that suit your garden. We agree materials and any features, such as lighting, as part of your quotation.`,
  footprintTitle: $localize`:@@site.commercial.footprintTitle:Swimming area is not the whole footprint`,
  footprintBody: $localize`:@@site.commercial.footprintBody:The square metres in the packages refer to swimming space. Allow room for filtration, edges, access and the surrounding places where you want to sit or move around. We plan these together before recommending a layout.`,
  ownershipTitle: $localize`:@@site.commercial.ownershipTitle:Budget for life with the pool`,
  ownershipBody: $localize`:@@site.commercial.ownershipBody:A nature pool needs routine care and electricity for circulation. Your system, operating time, water needs and choice of servicing affect running costs. We explain the tasks at handover and provide a maintenance plan; biological filtration does not mean no maintenance.`,
  pricingQuestionTitle: $localize`:@@site.commercial.pricingQuestionTitle:Do I need to choose a package before we talk?`,
  pricingQuestionBody: $localize`:@@site.commercial.pricingQuestionBody:No. The packages help you compare scale and investment. You can enquire about one or leave the choice open. We start with your garden, the way you want to use it and your budget.`,
  waterPriceTitle: $localize`:@@site.commercial.waterPriceTitle:Prices for ponds, streams and fountains`,
  waterPriceBody: $localize`:@@site.commercial.waterPriceBody:These are separate projects from the swimming-pool packages. We discuss the site, size, circulation and materials with you and provide an individual quotation.`,
  waterfallPriceTitle: $localize`:@@site.commercial.waterfallPriceTitle:Streams and waterfalls`,
  waterfallPriceBody: $localize`:@@site.commercial.waterfallPriceBody:The length, levels and access for equipment affect the design. Tell us where you would like to hear and see the water; we work out the scope before quoting.`,
  fountainPriceTitle: $localize`:@@site.commercial.fountainPriceTitle:Fountains and smaller water features`,
  fountainPriceBody: $localize`:@@site.commercial.fountainPriceBody:A fountain or small pond has its own requirements for water supply, circulation and installation. Ask us about your space; nature-pool starting prices do not apply to these installations.`,
  waterFeatureLink: $localize`:@@site.commercial.waterFeatureLink:Explore ponds, streams and waterfalls`,
} as const;

// Owner-approved indicative estimates; research and scope in docs/BUYING-EXPERIENCE-REVIEW.md.
export const POOL_COST_COMPARISON = {
  title: $localize`:@@site.comparison.title:Nature pool costs and care`,
  items: [
    {
      label: $localize`:@@site.comparison.investment:more to build`,
      value: $localize`:@@site.comparison.investmentValue:About 30%`,
      body: $localize`:@@site.comparison.investmentBody:A nature pool typically costs more upfront than a comparable conventional pool, including its biological filtration and planted areas.`,
    },
    {
      label: $localize`:@@site.comparison.running:less to run`,
      value: $localize`:@@site.comparison.runningValue:About 50%`,
      body: $localize`:@@site.comparison.runningBody:Biological filtration removes routine chlorine costs and can reduce operating costs compared with a conventional pool.`,
    },
    {
      label: $localize`:@@site.comparison.care:of weekly care`,
      value: $localize`:@@site.comparison.careValue:30–60 minutes`,
      body: $localize`:@@site.comparison.careBody:Care focuses on removing leaves, checking circulation and tending plants. Allow additional time for seasonal maintenance.`,
    },
  ],
} as const;
