/** Page-specific explanations; package facts and the enquiry flow keep their shared owners. */
export const NATURE_POOL_DETAILS = {
  filterLabel: $localize`:@@site.poolDetails.filterLabel:How your pool works`,
  filterTitle: $localize`:@@site.poolDetails.filterTitle:A place to swim. A system working around it.`,
  filterBody: $localize`:@@site.poolDetails.filterBody:Your swimming area is part of a connected water system. Leaves are collected, water passes through biological filtration, and a pump keeps it moving. We plan these parts together, so you have room to swim while the filtration fits into the garden.`,
  filterCollectTitle: $localize`:@@site.poolDetails.filterCollectTitle:Collect leaves and debris`,
  filterCollectBody: $localize`:@@site.poolDetails.filterCollectBody:A skimmer or intake area gathers floating debris where it can be removed, before it settles on the bottom.`,
  filterBioTitle: $localize`:@@site.poolDetails.filterBioTitle:Let biology do its part`,
  filterBioBody: $localize`:@@site.poolDetails.filterBioBody:Beneficial bacteria in the filter break down waste, while aquatic plants take up nutrients. The filter type and size depend on your pool.`,
  filterReturnTitle: $localize`:@@site.poolDetails.filterReturnTitle:Keep the water moving`,
  filterReturnBody: $localize`:@@site.poolDetails.filterReturnBody:A pump circulates water through the system and back into the swimming area. We plan the flow and leave access for servicing.`,
  filterAlt: $localize`:@@site.poolDetails.filterAlt:Architectural cutaway illustration of a natural swimming pool beside a planted gravel filter, showing the water, filter layers and a connecting pipe beneath the surface.`,
  fitLabel: $localize`:@@site.poolDetails.fitLabel:Designed for your garden`,
  fitTitle: $localize`:@@site.poolDetails.fitTitle:Naturally part of your garden. Beautifully part of your day.`,
  fitBody: $localize`:@@site.poolDetails.fitBody:Start with how you want to use the water: a quick dip, swimming or time together. We then look at the whole garden, including filtration, the way into the pool and somewhere to sit. You do not need to work out the layout before we talk.`,
  fitSwimTitle: $localize`:@@site.poolDetails.fitSwimTitle:Your swimming space`,
  fitSwimBody: $localize`:@@site.poolDetails.fitSwimBody:The package sizes refer to the water you swim in. Shape, depth and steps are part of the design conversation.`,
  fitFilterTitle: $localize`:@@site.poolDetails.fitFilterTitle:Room for filtration`,
  fitFilterBody: $localize`:@@site.poolDetails.fitFilterBody:Filtration and equipment need space beyond the swimming area, with access for care and servicing.`,
  fitEdgeTitle: $localize`:@@site.poolDetails.fitEdgeTitle:The way you use the garden`,
  fitEdgeBody: $localize`:@@site.poolDetails.fitEdgeBody:Stone edges, planting and a place to sit connect the pool to your home. We also assess ground levels and access for the build.`,
  fitAlt: $localize`:@@site.poolDetails.fitAlt:Concept image: a nature pool with a planted edge and stone steps leading from a timber terrace into the water in a leafy garden.`,
  fitCta: $localize`:@@site.poolDetails.fitCta:Find out what could fit`,
  everydayLabel: $localize`:@@site.poolDetails.everydayLabel:More time by the water`,
  everydayTitle: $localize`:@@site.poolDetails.everydayTitle:A garden you spend more of your life in.`,
  everydayBody: $localize`:@@site.poolDetails.everydayBody:You do not need a whole day free to enjoy the water. A nature pool brings swimming and time by the water into the garden you already call home.`,
  everydaySwimTitle: $localize`:@@site.poolDetails.everydaySwimTitle:A swim whenever it suits you`,
  everydaySwimBody: $localize`:@@site.poolDetails.everydaySwimBody:Before breakfast or after work, step outside for a dip without packing a bag or driving to the beach.`,
  everydayTogetherTitle: $localize`:@@site.poolDetails.everydayTogetherTitle:A place to linger`,
  everydayTogetherBody: $localize`:@@site.poolDetails.everydayTogetherBody:Bring your coffee to the water’s edge, read while someone swims, or stay outside a little longer when friends visit.`,
  everydayGardenTitle: $localize`:@@site.poolDetails.everydayGardenTitle:Something to enjoy beyond the swim`,
  everydayGardenBody: $localize`:@@site.poolDetails.everydayGardenBody:Stone, planting and changing reflections give you something to enjoy from the terrace or the house, even on days you never get in.`,
  everydayAlt: $localize`:@@site.poolDetails.everydayAlt:A couple sharing a smile at a garden nature pool, one in the water and the other sitting close beside them on the timber deck.`,
  careLabel: $localize`:@@site.poolDetails.careLabel:Life with your pool`,
  careTitle: $localize`:@@site.poolDetails.careTitle:Know what to do. Know who to ask.`,
  careBody: $localize`:@@site.poolDetails.careBody:Before your first season, we walk you through your own system and give you a care plan. You will know what to check, how to look after the plants and when to arrange seasonal help.`,
  careRoutineTitle: $localize`:@@site.poolDetails.careRoutineTitle:Your regular checks`,
  careRoutineBody: $localize`:@@site.poolDetails.careRoutineBody:Remove leaves and debris, check the water level and flow, and follow the cleaning instructions for your equipment.`,
  careSeasonTitle: $localize`:@@site.poolDetails.careSeasonTitle:A plan for the seasons`,
  careSeasonBody: $localize`:@@site.poolDetails.careSeasonBody:Your plan covers plant care, spring start-up and winter preparation for your particular pool.`,
  careSupportTitle: $localize`:@@site.poolDetails.careSupportTitle:Help when you need it`,
  careSupportBody: $localize`:@@site.poolDetails.careSupportBody:You can also arrange servicing, cleaning and seasonal help with us. We discuss the scope and cost separately.`,
  careAlt: $localize`:@@site.poolDetails.careAlt:Illustrative image: a fine-mesh net collecting fallen leaves beside the stone edge of a nature pool.`,
  careCaption: $localize`:@@site.poolDetails.careCaption:Everyday care starts at the water’s edge. Illustrative image.`,
  projectGardenTitle: $localize`:@@site.poolDetails.projectGardenTitle:Part of the garden`,
  projectGardenBody: $localize`:@@site.poolDetails.projectGardenBody:The pool sits beside Brita’s home, with planting and natural stone connecting the water to its surroundings.`,
  projectStoneTitle: $localize`:@@site.poolDetails.projectStoneTitle:Natural stone, above and below`,
  projectStoneBody: $localize`:@@site.poolDetails.projectStoneBody:The close-up shows the stone beneath the water and the texture that continues along the pool’s edge.`,
  projectEveningTitle: $localize`:@@site.poolDetails.projectEveningTitle:A different view after dark`,
  projectEveningBody: $localize`:@@site.poolDetails.projectEveningBody:Underwater lighting reveals the rocks and water after sunset, making the pool visible from the garden in the evening.`,
} as const;
