export const FAUNAPOOLEN_COMMERCIAL = {
  definitionTitle: $localize`:@@site.commercial.definitionTitle:A place to swim, part of your garden`,
  definitionBody: $localize`:@@site.commercial.definitionBody:A nature pool combines a swimming area with biological filtration. You may also encounter the terms swimming pond, biopool or ecological pool; the names do not tell you exactly how a system works. We plan the swimming area, filtration and surroundings together, for your property.`,
  spaceGuideLink: $localize`:@@site.commercial.spaceGuideLink:How much space does a nature pool need?`,
  processGuideLink: $localize`:@@site.commercial.processGuideLink:Read about the steps from first call to swimming`,
  filterLink: $localize`:@@site.commercial.filterLink:How biological filtration works`,
  seasonalCareLink: $localize`:@@site.commercial.seasonalCareLink:Read about care through the year`,
  ownershipGuideLink: $localize`:@@site.commercial.ownershipGuideLink:What affects the running cost?`,
  careLink: $localize`:@@site.commercial.careLink:Read about algae and maintenance`,
  poolLink: $localize`:@@site.commercial.poolLink:Explore our nature pools`,
  packageLink: $localize`:@@site.commercial.packageLink:Find a pool package for your garden`,
  projectBridgeTitle: $localize`:@@site.commercial.projectBridgeTitle:What would your own swimming spot look like?`,
  projectBridgeBody: $localize`:@@site.commercial.projectBridgeBody:This is one finished project. Your swimming area, edges and planting will be designed for your property and the way you want to use it. Compare our pool options to find a starting point.`,
  caseStoryTitle: $localize`:@@site.commercial.caseStoryTitle:A swimming spot beside the house`,
  caseStoryBody: $localize`:@@site.commercial.caseStoryBody:We built this nature pool beside Brita’s home on southern Gotland. The photographs show the pool, its stone edges and the surrounding garden. Brita describes both the build and the time she and her grandchildren have spent in the water.`,
  swimmingTitle: $localize`:@@site.commercial.swimmingTitle:Would you like to swim, too?`,
  swimmingBody: $localize`:@@site.commercial.swimmingBody:A pond or stream gives you a place to spend time beside the water. If swimming is part of your plan, explore a nature pool with a swimming area and filtration designed for that purpose.`,
  gardenGuideLink: $localize`:@@site.commercial.gardenGuideLink:Plan water features with your garden`,
  waterscapeArea: $localize`:@@site.commercial.waterscapeArea:We design water features throughout Sweden and in Denmark. Tell us about your garden and we will discuss the right scope; ponds and streams are quoted individually.`,
  areaTitle: $localize`:@@site.commercial.areaTitle:Nature pools in southern Sweden`,
  areaBody: $localize`:@@site.commercial.areaBody:We build nature pools throughout Sweden and in Denmark. Here you can explore local planning questions for Skåne, Halland, Blekinge and Småland. Wherever your property is, start by telling us about the place and your ideas.`,
  pricingTitle: $localize`:@@site.commercial.pricingTitle:What does a nature pool cost?`,
  pricingIntro: $localize`:@@site.commercial.pricingIntro:Our three options show indicative starting prices, including VAT. The final quotation depends on the property, access and the work and materials we agree with you.`,
  scopeTitle: $localize`:@@site.commercial.scopeTitle:What does your pool package cover?`,
  scopeBody: $localize`:@@site.commercial.scopeBody:The options describe a scale and design direction, not a fixed specification for every garden. The quotation sets out the actual work and materials: groundwork, pool construction, filtration, edges and planting, together with any agreed additions. A planned feature is not automatically an installed feature.`,
  scopeDetail: $localize`:@@site.commercial.scopeDetail:We clarify access, excavation and removal of soil, electrical work, water filling, transport and handover before you accept the quotation. The first phone consultation is free; any site visit is charged and its fee is credited against installation if you proceed.`,
  costTitle: $localize`:@@site.commercial.costTitle:What affects the cost of a nature pool?`,
  groundTitle: $localize`:@@site.commercial.groundTitle:Ground and access`,
  groundBody: $localize`:@@site.commercial.groundBody:The ground, levels and route for machinery affect the work involved. These need to be assessed for your property before the quotation can be settled.`,
  sizeTitle: $localize`:@@site.commercial.sizeTitle:Swimming area and filtration`,
  sizeBody: $localize`:@@site.commercial.sizeBody:The size and way you want to swim guide the layout. Filtration and circulation are planned for the installation; a larger swimming area also changes the work around it.`,
  surroundingsTitle: $localize`:@@site.commercial.surroundingsTitle:Materials and the surrounding garden`,
  surroundingsBody: $localize`:@@site.commercial.surroundingsBody:Edging, steps, planting and the connection to a terrace are part of the design choices. Lighting or a waterfall can be discussed and priced as part of the agreed scope.`,
  footprintTitle: $localize`:@@site.commercial.footprintTitle:Swimming area is not the whole footprint`,
  footprintBody: $localize`:@@site.commercial.footprintBody:The square metres in the packages refer to swimming space. Allow room for filtration, edges, access and the surrounding places where you want to sit or move around. We plan these together before recommending a layout.`,
  ownershipTitle: $localize`:@@site.commercial.ownershipTitle:Budget for life with the pool`,
  ownershipBody: $localize`:@@site.commercial.ownershipBody:A nature pool needs routine care and electricity for circulation. Your system, operating time, water needs and choice of servicing affect running costs. We explain the tasks at handover and provide a maintenance plan; biological filtration does not mean no maintenance.`,
  pricingQuestionTitle: $localize`:@@site.commercial.pricingQuestionTitle:Do I need to choose a package before we talk?`,
  pricingQuestionBody: $localize`:@@site.commercial.pricingQuestionBody:No. The packages help you compare scale and investment. You can enquire about one or leave the choice open. We start with your garden, the way you want to use it and your budget.`,
  waterPriceTitle: $localize`:@@site.commercial.waterPriceTitle:Prices for ponds, streams and fountains`,
  waterPriceBody: $localize`:@@site.commercial.waterPriceBody:These are separate projects from the swimming-pool packages. We discuss the site, size, circulation and materials with you and provide an individual quotation.`,
  waterfallPriceTitle: $localize`:@@site.commercial.waterfallPriceTitle:Streams and waterfalls`,
  waterfallPriceBody: $localize`:@@site.commercial.waterfallPriceBody:The length, levels and access for equipment affect the design. Tell us where you would like to hear and see the water; we work out the scope before quoting.`,
  fountainPriceTitle: $localize`:@@site.commercial.fountainPriceTitle:Fountains and smaller water features`,
  fountainPriceBody: $localize`:@@site.commercial.fountainPriceBody:A fountain or small pond has its own requirements for water supply, circulation and installation. Ask us about your space; nature-pool starting prices do not apply to these installations.`,
  waterFeatureLink: $localize`:@@site.commercial.waterFeatureLink:Explore ponds, streams and waterfalls`,
} as const;
