/** Buying questions and supporting copy shared by the bilingual page compositions. */
export const FAUNAPOOLEN_EDITORIAL = {
  heroAlt: $localize`:@@site.editorial.heroAlt:Concept image: a couple enjoying a nature pool at dusk, with warm garden lights.`,
  architectureAlt: $localize`:@@site.editorial.architectureAlt:Concept image: a view from a timber house towards water and woodland.`,
  waterscapeAlt: $localize`:@@site.editorial.waterscapeAlt:Concept image: a koi pond and a small stream in a leafy garden.`,
  supplierAlt: $localize`:@@site.editorial.supplierAlt:Aquascape’s own example of a recreational pond.`,
  responsibility: $localize`:@@site.editorial.responsibility:From design to construction and care. Faunapoolen brings your project together.`,
  lifeTitle: $localize`:@@site.editorial.lifeTitle:You do not need a finished plan.`,
  lifeBody: $localize`:@@site.editorial.lifeBody:We help you find a solution for the way you want to use your garden, the conditions on your property and your budget.`,
  lifeLink: $localize`:@@site.editorial.lifeLink:Explore our nature pools`,
  customerTitle: $localize`:@@site.editorial.customerTitle:It’s the life around the pool that matters.`,
  britaContext: $localize`:@@site.editorial.britaContext:Brita shares her experience of the build and life with her nature pool on southern Gotland.`,
  casePreview: $localize`:@@site.editorial.casePreview:Explore the finished nature pool through photographs and films from Gotland.`,
  firstContact: $localize`:@@site.editorial.firstContact:Your first phone consultation is free.`,
  certificationMeaning: $localize`:@@site.editorial.certificationMeaning:What the certification means`,
  technologyResponsibility: $localize`:@@site.editorial.technologyResponsibility:The technology comes from Aquascape. We select and adapt the system for your site, and show you how to care for it.`,
  technologyDetails: $localize`:@@site.editorial.technologyDetails:How filtration and care work`,
  priceScope: $localize`:@@site.editorial.priceScope:Indicative starting prices include VAT. Ground conditions, access and your choices affect the quotation, which sets out the work and materials included.`,
  discussService: $localize`:@@site.editorial.discussService:Ask us about this`,
  service: $localize`:@@site.editorial.service:What are you interested in?`,
  unknown: $localize`:@@site.editorial.unknown:Not sure yet`,
  servicePrice: $localize`:@@site.editorial.servicePrice:We’ll assess the cost together`,
  servicePriceBody: $localize`:@@site.editorial.servicePriceBody:Tell us about the site and what you have in mind. You do not need to choose a pool package to begin.`,
  packageHelp: $localize`:@@site.editorial.packageHelp:Packages are a starting point. You can leave the choice open.`,
  optionalChoices: $localize`:@@site.editorial.optionalChoices:Personalise your pool`,
  optionalChoicesBody: $localize`:@@site.editorial.optionalChoicesBody:Choose what you already know. We can work out the rest together.`,
  contactHelp: $localize`:@@site.editorial.contactHelp:Your name, email and location are needed for the brief. Phone and preferred contact time are optional.`,
  notes: $localize`:@@site.editorial.notes:Your ideas or questions`,
  notesHelp: $localize`:@@site.editorial.notesHelp:For example, how you would like to use the space and when you would like to begin.`,
  review: $localize`:@@site.editorial.review:Review your project brief`,
  estimatePending: $localize`:@@site.editorial.estimatePending:Ground conditions and access still need to be assessed.`,
  videoLink: $localize`:@@site.editorial.videoLink:Watch on YouTube`,
  guideContents: $localize`:@@site.editorial.guideContents:In this guide`,
  spaceTitle: $localize`:@@site.sales.spaceTitle:Will a nature pool fit your garden?`,
  spaceBody: $localize`:@@site.sales.spaceBody:The swimming area is only part of the space needed. We assess filtration, access, ground conditions and the places around the pool before proposing a layout.`,
  priceLink: $localize`:@@site.sales.priceLink:See nature pool prices and packages`,
  caseStory: $localize`:@@site.sales.caseStory:Built by us beside Brita’s home on southern Gotland, and enjoyed by her and her grandchildren.`,
  caseExperience: $localize`:@@site.sales.caseExperience:Brita on the build`,
  caseLife: $localize`:@@site.sales.caseLife:Life with the pool`,
  faqLink: $localize`:@@site.sales.faqLink:Questions about space, costs or care?`,
  packageDesign: $localize`:@@site.sales.packageDesign:Design`,
  packageFiltration: $localize`:@@site.sales.packageFiltration:Filtration`,
  packageSurroundings: $localize`:@@site.sales.packageSurroundings:Around the pool`,
} satisfies Record<string, string>;

export const FAUNAPOOLEN_SERVICES = [
  { id: 'pool', name: $localize`:@@site.services.pool.name:Nature pool` },
  { id: 'pond', name: $localize`:@@site.services.pond.name:Pond` },
  {
    id: 'stream',
    name: $localize`:@@site.services.stream.name:Stream or waterfall`,
  },
  {
    id: 'unsure',
    name: $localize`:@@site.services.unsure.name:I would like help choosing`,
  },
] as const;
export type FaunapoolenService = (typeof FAUNAPOOLEN_SERVICES)[number]['id'];
