/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.5-common-problems-installing-a-nature-pool.bodyHtml:<h2>An unbalanced ecosystem can lead to algal blooms and murky water</h2>
<p>One of the biggest problems with a nature pool is that the ecosystem becomes unbalanced, which can lead to severe algal blooms and murky water. To avoid this, it's important to maintain a good balance between plants and microorganisms. Water-purifying plants like reeds and water lilies help filter the water naturally, and a pump can ensure that the water remains in motion. Since a natural pool lacks chemicals, it takes time for the ecosystem to stabilize, but with proper planning, you'll achieve crystal-clear bathing water.</p>
<h2>Incorrect placement can lead to too much sun or shade</h2>
<p>The placement of your natural pool plays a crucial role in water quality. Too much direct sunlight can lead to increased algal growth, while too much shade can hinder the growth of aquatic plants. Ideally, place the pool where it receives sun for a few hours a day but also some shading, such as from strategically placed trees or shrubs. Floating plants can also help create natural shading and thus reduce the risk of algal problems.</p>
<h2>Leaks and poor insulation can cause major problems</h2>
<p>If the pool is not sealed properly, water leakage can cause major issues. Many use the wrong materials or neglect sealing, leading to increased maintenance costs. To avoid this, you should use a rubber liner or special clay to create a secure seal. It's also important to check the soil conditions before you start digging and ensure that the pool's construction is stable. A careful installation from the start saves both time and money in the long run.</p>
<h2>Poor circulation can lead to stagnant water and low oxygen levels</h2>
<p>If the water in your nature pool does not circulate sufficiently, it can become stagnant and start to smell bad. Poor oxygenation can also negatively affect the ecosystem. To solve this, you can install a low-energy pump that keeps the water in motion. A small stream or waterfall can also contribute to natural oxygenation. Avoid building too deep areas where oxygen supply becomes too low, and ensure that water flow is evenly distributed throughout the pool.</p>
<h2>Incorrect plant selection can lead to ineffective water purification</h2>
<p>Not all plants work equally well in a nature pool, and if you choose the wrong varieties, the water can quickly become dirty as the plants do not filter out nutrients effectively enough. It's important to use plants like reeds, eelgrass, and water clover to purify the water. By combining floating plants with rooted aquatic plants, you achieve effective filtration. Also, ensure to choose plants that thrive in your climate and in the pool's various depths to ensure a long-term sustainable solution.</p>`;
