/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.bodyHtml:<p>Collecting rainwater can supplement garden watering when a well is not available. It does not create a continuous supply: the result depends on rainfall, the collecting surface, storage and demand. Begin with the intended use, then calculate whether the water available is useful for that purpose.</p>
<h2>What will the collected water be used for?</h2>
<p>Watering planting, replenishing a decorative feature and supplying a swimming system are different uses. Record them separately, including when each needs water. The quality requirements and equipment must match the use. Water collected from a roof should not be assumed to be drinking water or ready for bathing.</p>
<p>For a pond or other feature, start with the kind of <a href="/en/waterscapes/">garden water landscape</a> you are planning. Its water needs belong in the same discussion as the collection system.</p>
<h2>How much can the roof and storage provide?</h2>
<p>One millimetre of rain over one square metre corresponds to one litre before losses. For example, 10 millimetres on a 100-square-metre roof gives a theoretical 1,000 litres. This is an illustrative calculation, not a prediction of the amount reaching a tank: collection losses, filtering, overflow and existing tank contents affect what can be stored.</p>
<p>Compare local rainfall patterns with the periods when you need water. Annual rainfall alone does not show whether a tank will contain enough during a dry spell. Estimate demand over that period and examine both a small and a larger storage option before choosing a size.</p>
<h2>Plan cleaning, filtration and access</h2>
<p>Draw the route from the roof through collection and filtering to storage and intended use. Consider how leaves and sediment are removed, how equipment is reached and where overflow goes. Cleaning should remain possible after paving and planting are in place.</p>
<p>Aquascape™ describes modular storage in its rainwater collection products, including AquaBlox used within a lined reservoir. The modules provide storage structure; the full installation still needs a design for its site and use. This product example does not establish what is included in a Faunapoolen quotation.</p>
<h2>Assess suitability before using it in a nature pool</h2>
<p>Discuss the proposed water source with the person responsible for the pool's design and water-quality plan. What reaches the roof and storage can affect the water collected. A general <a href="/en/blog/posts/how-filtering-works-with-nature-pools.html">biological cleaning system</a> does not by itself establish that every source is suitable for swimming.</p>
<h2>Allow for drought and check current local conditions</h2>
<p>When no rain arrives, a store can run out. Plan which uses take priority and what happens when the level is low. Before agreeing the installation or a filling plan, check current requirements with the relevant water provider and municipality. Any connection to another water supply needs appropriate professional assessment.</p>
<h2>Plan storage together with the garden</h2>
<p>Location affects excavation, access, the route to planting and future servicing. The <a href="/en/blog/posts/creating-harmony-intergrating-water-features-with-your-landscape.html">garden-planning guide</a> helps you consider those relationships before the visible surfaces are finished.</p>
<p>Have a roof sketch, photographs, intended uses and an estimate of demand ready. <a href="/en/configure/">Describe your garden and water-storage question</a> in the enquiry notes, so we can discuss the scope and whether we can help with your project.</p>`;
