/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.how-faunapoolen-helps-golf-clubs-manage-ponds-lakes-and-streams.bodyHtml:<p>A useful plan for golf-course ponds and streams begins with their function. A visible water feature, an irrigation store and a part of the drainage system may look similar, but they serve different purposes. Record those purposes before choosing maintenance work or new equipment.</p>
<h2>Define each pond's role on the course</h2>
<p>Give every pond and stream an identifier on the course plan. Note whether it is used for irrigation, receives runoff, has a landscape role or fulfils several functions. Identify who manages it and what information is already available about its construction and operation.</p>
<p>A water level that suits one purpose may conflict with another. Record the desired conditions and known limitations so that an assessment starts with the course's requirements rather than a generic garden-pond solution.</p>
<figure><img src="/assets/images/blog/18.webp" alt="Golfer taking a shot on a course bordered by trees" loading="lazy" /><figcaption>Illustrative golf-course photograph, not a documented Faunapoolen customer project.</figcaption></figure>
<h2>Inventory flows, banks and existing equipment</h2>
<p>Mark known inlets, outlets, overflow routes, pumps and pipes. Add accessible records of water levels and changes after rain or irrigation. Note damage at banks, difficult access points and places where debris collects. Photographs taken from the same position make changes easier to compare.</p>
<p>This inventory is a starting point for investigation, not a substitute for a hydrological or engineering assessment. Unknown connections and changes affecting other land need the appropriate expertise.</p>
<h2>Track sediment, plants and water quality</h2>
<p>Keep observations of sediment, plant growth, odour and water appearance together with maintenance records. If an issue recurs, note the timing, weather and work performed before it appeared. A consistent record is more useful than treating every change as an isolated event.</p>
<p>Our article on <a href="/en/blog/posts/algae-control-and-maintenance-tips.html">algae in ponds</a> explains initial observations. Any treatment must be assessed for the actual water use, connected environments and applicable requirements.</p>
<h2>Plan work around the season and play</h2>
<p>Coordinate access for equipment with course operations. Agree where removed material can be handled, which areas need protection and how the site is left after work. Give recurring checks a named owner, a schedule suited to the installation and a way to report changes that need attention.</p>
<p>For supplementary storage questions, read the <a href="/en/blog/posts/can-i-use-water-storage-solutions-when-traditional-wells-arent-an-option.html">rainwater collection article</a>. A garden-storage example is not a design for course-wide irrigation; demand and supply need their own assessment.</p>
<figure><img src="/assets/images/blog/19.webp" alt="Water and surrounding planting in a golf-course setting" loading="lazy" /><figcaption>Access and surrounding ground belong in the maintenance discussion as well as the water itself.</figcaption></figure>
<h2>Identify questions that need specialist assessment</h2>
<p>Changes to water levels, outlets, excavation or connections to other waters can require specialist investigation and contact with the responsible authority. Establish what applies to the particular site before commissioning that work. Ask prospective suppliers to describe the work they can undertake and any specialists needed.</p>
<p>For projects in Sweden, the Swedish Agency for Marine and Water Management provides guidance on notification of water operations. Use it to prepare questions for the responsible authority; it does not determine the requirements for a particular course.</p>
<h2>Prepare for an initial conversation</h2>
<ul><li>A course plan showing the relevant waters and known connections.</li><li>Photos, approximate dimensions and existing equipment details.</li><li>The function of each water body and the issue you want to resolve.</li><li>Available records, previous work and seasonal access constraints.</li><li>The person responsible for the decision and ongoing care.</li></ul>
<p>Our <a href="/en/waterscapes/">water-landscape page</a> shows the kinds of features we discuss. <a href="/en/configure/">Describe the course's water features</a> in the enquiry notes, including the location and intended work. We can then discuss whether the project fits our scope and what needs assessing first.</p>`;
