/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.naturpool-i-sodra-sverige.bodyHtml:<h2>A nature pool that belongs in your garden</h2>
<p>A morning dip before work, a swim with the children or an evening beside the water: start with the moments you want to make room for. A nature pool brings swimming and garden design together, with biological filtration planned as part of the installation. The shape, edges and planting should suit both the house and the way you use the space.</p>
<p>Faunapoolen designs and builds nature pools in southern Sweden, including Skåne, Halland, Blekinge and Småland. We also work throughout Sweden and in Denmark. You do not need a finished drawing to begin a conversation about a pool we can build for you.</p>
<h2>Planning a nature pool in Skåne, Halland, Blekinge or Småland</h2>
<p>Whether your garden is in Malmö, Lund, Helsingborg, Halmstad, Karlskrona or Växjö, the property matters more than the postcode. Two nearby gardens can call for different layouts, ground preparation and construction access. A regional search is a useful way to find a pool builder; the proposal still needs to start with your own site.</p>
<p>Show us the route from the house, places where you enjoy sitting and views you want to keep. Note slopes, trees, narrow gates and any areas where water collects after rain. For an exposed garden, include where you find shelter and sun; beside mature planting, consider how the pool and its equipment will be reached for care.</p>
<h2>Allow space for more than swimming</h2>
<p>The swimming area is only part of a natural pool. Filtration, equipment, edges and paths also need a place in the design. A compact pool with comfortable surroundings can offer more day-to-day enjoyment than a larger pool that leaves no room to sit or move around it.</p>
<p>Our <a href="/en/blog/posts/hur-mycket-plats-behover-en-naturpool.html">guide to the space a nature pool needs</a> helps you think about the whole installation. For a real example of our work, explore <a href="/en/projects/gotland/">Brita’s pool on Gotland</a>, with its natural stone edges and surrounding garden.</p>
<h2>Budget for a complete installation</h2>
<p>When comparing the cost of a nature pool in southern Sweden, look beyond the swimming area. Ask what is included in excavation, handling of excavated material, filtration, planting and the finished surround. Access and ground conditions can change the work required, so a starting price is a guide rather than a quotation for your property.</p>
<p><a href="/en/nature-pools/pricing/">Compare our nature pool sizes and starting prices</a>, then consider which scale fits your plans. We develop the design and quotation around the site, your priorities and the agreed scope, so you can decide with a clearer picture of the project.</p>
<h2>From an idea to a pool built by Faunapoolen</h2>
<p>Bring a few garden photographs, your location, an approximate budget and your preferred timing to the first conversation. We will discuss what you want from the pool and how to take the project forward. A site visit is agreed separately and charged, with the fee credited against installation if you proceed.</p>
<p>You can read more about <a href="/en/blog/posts/naturpool-fran-forsta-samtal-till-bad.html">our process from the first conversation to handover</a>. The aim is a pool designed for your home, with the construction, surroundings and future care considered together.</p>`;
