/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.naturpool-pris.bodyHtml:<p>A useful nature pool budget covers more than the water you swim in. It includes the system that cleans it, the work below ground and the edges that connect it to your garden. Start with our <a href="/en/nature-pools/pricing/">nature pool packages and current prices</a>, then use this guide to understand what is included and what needs a separate allowance.</p>
<h2>What is included in the price of a nature pool?</h2>
<p>A nature pool quotation should make the whole installation understandable: design, excavation, liner, filtration, pumps, pipework, stone edges and planting. Check which work is covered by the starting price and which items depend on your site. Start-up, care instructions and any follow-up should be described too. Our package overview is the starting point; the quotation for your garden confirms the agreed work.</p>
<p>Commissioning an installation is different from buying a liner and pump for a project you build yourself. When comparing nature pool prices, compare the finished work and responsibilities as well as the equipment. A low material price does not tell you the cost of an installed pool.</p>
<p>Biological filtration needs its own space and a planned flow of water. It belongs in the initial design and budget, together with the swimming area. Our <a href="/en/blog/posts/how-filtering-works-with-nature-pools.html">guide to nature pool filtration</a> explains what that part of the installation does.</p>
<h2>What changes the cost of installing a nature pool?</h2>
<h3>Ground conditions and access</h3>
<p>A level garden with a clear route for machinery calls for different work from a steep site behind a narrow gate. Rock excavation, groundwater work and restricted access are assessed separately. Removal and disposal of surplus soil also need to be included in the quotation; a place to dig is not necessarily a place to leave everything that comes out.</p>
<h3>Swimming area and the whole footprint</h3>
<p>A larger pool needs more excavation, lining and a filtration system suited to its size and use. The swimming area is only part of the footprint: edges, filtration and access take space too. Before comparing prices per square metre, check whether the quoted area means swimming water or the entire installation.</p>
<h3>Stone, planting and the surrounding garden</h3>
<p>Compare the proposed stone edges and aquatic planting, and check whether the price also covers terraces, decks or landscaping beyond the pool. Think about the route from the house, where you will sit and how you will reach the equipment. These choices can change the total budget even when the swimming area stays the same.</p>
<figure><img src="/assets/images/guides/inline/price-stone-and-planting.webp" alt="Natural stone coping and aquatic planting at the edge of a nature pool." width="1536" height="1024" loading="lazy" /><figcaption>Plan the pool edge and planting together with the paths and seating you want around the water.</figcaption></figure>
<h3>Services, transport and heating</h3>
<p>Check how the quotation accounts for electrical supply, water filling and transport, including any separate charges. If you want warmer swims or a longer season, discuss heating and a suitable cover as part of the design. Neither should be assumed to be included in a package starting price. Our <a href="/en/blog/posts/varma-upp-naturpool.html">guide to heating a nature pool</a> covers those choices.</p>
<h2>Does a small nature pool cost less?</h2>
<p>A smaller swimming area can reduce materials and excavation, but a small nature pool still needs reliable filtration, circulation and careful installation. Its price does not fall in direct proportion to its area. Difficult access or ground conditions can also make a compact project more involved than its size suggests.</p>
<p>Begin with the way you want to use the water. A short dip after a sauna needs a different layout from swimming with the family. Our smallest starting package has a swimming area from 17.5 m². The full installation needs more room for filtration and edges, with paths and terraces considered as well. Read <a href="/en/blog/posts/hur-mycket-plats-behover-en-naturpool.html">how much space a nature pool needs</a> before measuring only the water.</p>
<h2>How to compare nature pool quotations</h2>
<p>Ask each supplier to describe the same finished project. A useful comparison makes the scope, exclusions and responsibilities visible. Check these points together:</p>
<ul><li>The swimming area, depth and space for filtration.</li><li>Design, excavation and any assumptions about ground conditions.</li><li>Soil removal, transport, electrical supply and filling.</li><li>Liner, pumps, filtration, pipework and installation.</li><li>Stone edges, aquatic planting and any separate garden work.</li><li>Start-up, handover, care instructions and follow-up.</li><li>VAT, payment terms and how changes to the agreed work are priced.</li></ul>
<p>For a Faunapoolen project, the quotation should make the agreed scope and site-specific costs clear before construction. Use the <a href="/en/nature-pools/pricing/">package overview</a> to compare our starting scopes, then read <a href="/en/blog/posts/naturpool-fran-forsta-samtal-till-bad.html">how a Faunapoolen project develops</a> to see what happens between an idea and handover.</p>
<h2>What does a nature pool cost to run?</h2>
<p>The construction price and annual running costs answer different questions. Biological filtration replaces routine chlorine dosing, but circulation still uses electricity and the pool still needs care. Water top-ups, optional heating, service visits and eventual repairs also belong in the ownership budget.</p>
<p>There is no single annual figure that fits every installation. Equipment, operating hours, the swimming season and how much care you do yourself all matter. Our <a href="/en/blog/posts/vad-kostar-det-att-aga-en-naturpool.html">nature pool running-cost guide</a> shows how to calculate a budget, while the <a href="/en/blog/posts/din-naturpool-skotsel-efter-installation.html">aftercare checklist</a> explains the routine.</p>
<h2>See what the investment can become</h2>
<p>A price list helps establish the scale of the decision. A real garden shows how a pool can fit into everyday life. Explore <a href="/en/projects/gotland/">Brita’s nature pool on Gotland</a> for a completed Faunapoolen project, its setting and photographs. It is an example of our work, not a quotation or a promise that another property will cost the same.</p>
<p>When you have a sense of your budget, <a href="/en/nature-pools/">explore our nature pools</a> and consider the space, swimming and garden you want. You do not need to choose a package yet. The aim is to find a scale that feels right and understand what your own site would add to the starting price.</p>`;
