/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.pool-conversions.bodyHtml:<p>Converting an existing pool to a nature pool may be possible, but changing the cleaning system is only part of the work. The structure, sealing, pipework and garden must suit the proposed design. A site assessment establishes what is worth keeping and whether conversion is a sensible starting point.</p>
<h2>Start with the condition of the existing pool</h2>
<p>Collect drawings and information about the pool's age, construction and previous repairs. Cracks, unexplained water loss or changes to the surrounding ground need investigating before a new finish conceals them. The existing pool shape can inform the design; it does not establish that the structure is suitable.</p>
<figure><img src="/assets/images/guides/inline/conversion-existing-shell.webp" alt="An older pool corner with weathered coping and a surface crack." width="1536" height="1024" loading="lazy" /><figcaption>Inspect the shell, coping and surrounding ground before deciding what can be reused.</figcaption></figure>
<h2>Allow space for cleaning and circulation</h2>
<p>A biological cleaning system needs room and a planned route for the water. Its layout depends on the bathing area, intended use and chosen equipment. Consider access to pumps and collection points at the same time as the visible pool edge.</p>
<p>Read <a href="/en/blog/posts/how-filtering-works-with-nature-pools.html">how nature-pool filtration works</a> to see why debris collection, biological processes and circulation must be planned together.</p>
<figure><img src="/assets/images/guides/inline/conversion-filter-space.webp" alt="A proposed filtration area marked out on grass beside an existing pool." width="1536" height="1024" loading="lazy" /><figcaption>Include the filtration area and maintenance access when measuring the space around the existing pool.</figcaption></figure>
<h2>Decide what can stay</h2>
<p>A survey should separate usable elements from those requiring repair or replacement. Discuss the shell, waterproofing, pipes, electrical equipment, steps and surrounding paving individually. Retaining an element is useful only if it suits the new system and remains accessible for maintenance.</p>
<figure><img src="/assets/images/guides/inline/conversion-retained-steps.webp" alt="Existing pool steps, handrail and paving beside the water." width="1536" height="1024" loading="lazy" /><figcaption>Assess steps, edges and other existing parts individually before including them in the new design.</figcaption></figure>
<h2>Agree the process before construction</h2>
<p>The first conversation establishes your wishes and what is known about the pool. The next assessment must define the proposed solution, work scope and remaining uncertainties before a quotation or construction schedule can be meaningful. Ask who is responsible for each stage and how unexpected structural work would be handled.</p>
<h2>Understand what drives the cost</h2>
<p>Access for machinery, removal of old materials, structural repairs, new cleaning equipment and changes around the pool all affect the work. Reusing a shell does not automatically make conversion cheaper than a new installation.</p>
<p>Our <a href="/en/nature-pools/pricing/">nature-pool packages and starting prices</a> describe new-build alternatives. They are useful for comparing options, but they are not conversion quotations.</p>
<figure><img src="/assets/images/guides/inline/conversion-site-access.webp" alt="A compact excavator on ground protection boards beside a garden access route." width="1536" height="1024" loading="lazy" /><figcaption>Access for machinery and protection of the garden affect the work and its cost.</figcaption></figure>
<h2>Plan commissioning and ongoing care</h2>
<p>A changed system needs a commissioning and care plan. Ask how operation and water quality will be checked, when bathing can begin and what you will need to monitor. The bathing start date should follow the agreed commissioning checks for the completed system.</p>
<p>If you are still choosing between pool types, the <a href="/en/blog/posts/difference-between-normal-pool-and-natural-pool.html">comparison of conventional and natural pools</a> explains the different approaches.</p>
<figure><img src="/assets/images/guides/inline/conversion-water-check.webp" alt="A hand holding a clear water sample beside a nature pool." width="1536" height="1024" loading="lazy" /><figcaption>Water checks belong in the commissioning plan before bathing begins.</figcaption></figure>
<h2>Gather these details for the first conversation</h2>
<ul><li>Photos of the pool, equipment and surrounding access.</li><li>Dimensions, drawings and known construction materials.</li><li>Details of leaks, repairs and existing treatment equipment.</li><li>Your desired bathing area, garden changes and budget.</li></ul>
<p><a href="/en/configure/?service=pool">Tell us about your existing pool</a>. Describe it in the enquiry notes so we can discuss whether further assessment is appropriate.</p>`;
