/** English editorial source; translations are owned by Angular i18n catalogues. */
export const BODY_HTML = $localize`:@@blog.skotsel-av-naturpool-under-aret.bodyHtml:<h2>Begin with the plan for your pool</h2>
<p>Natural filtration does not remove the need for care. At handover, make sure you understand which checks you can do, which tasks need a specialist and what changes between swimming season and winter. Keep the component names, manuals and contact details together so that advice can be matched to the equipment actually installed.</p>
<p>A useful care plan names the task, what prompts it and how to recognize a problem. “Check regularly” is less helpful than knowing the normal water level and where to look for a reduced flow. Avoid borrowing a cleaning schedule from another pool merely because it looks similar. The <a href="/en/blog/posts/how-filtering-works-with-nature-pools.html">filtration guide</a> explains the parts of the system in more detail.</p>
<h2>Spring: inspect before restarting</h2>
<p>Walk around the pool after winter. Look at the edges, access points and visible equipment, and record anything that has moved, cracked or become difficult to reach. Check what was disconnected or stored before restarting. Follow the installed system's sequence rather than switching everything on to see what happens.</p>
<p>In its <a href="https://gb.bio.top/service-during-the-year">seasonal care overview</a>, natural-pool manufacturer Biotop includes plant care, circulation restart and removal of bottom sediment among spring tasks. That is an example from its own systems, not a universal timetable or confirmation that your pool uses Biotop equipment.</p>
<p>Ask which checks must be completed before swimming resumes, and arrange any required inspection in advance. A calendar date or a clear-looking surface alone should not be your handover criterion. Keep observations and any agreed measurements in a short record that is useful if a question arises later.</p>
<h2>Summer: learn what normal looks like</h2>
<p>Notice the water level, visible flow and collection of surface debris during ordinary use. Check baskets or screens as specified for your installation, especially after windy weather. Aquascape's <a href="https://support.aquascapeinc.com/hc/en-us/article_attachments/360087330952">pond-system instructions</a> explain that excessive debris in the collection net can restrict flow. Their detailed procedures concern that equipment; use your own manual for cleaning and isolation.</p>
<p>Record unusual water loss rather than continually topping up without investigation. Note when it began, recent weather and whether the circulation setting changed. Check local filling restrictions before adding water. If the appearance or smell changes unexpectedly, pause swimming and ask for an assessment instead of choosing a treatment from a photograph.</p>
<p>For algae questions, start with our <a href="/en/blog/posts/algae-control-and-maintenance-tips.html">algae and maintenance guide</a>. Avoid adding products or changing filtration settings without confirming their suitability for your swimming system.</p>
<h2>Autumn: prepare before the first frost</h2>
<p>Give leaf collection more attention as nearby trees shed their leaves. Decide how leaves will be removed without making the water harder to supervise. A leaf net must not be mistaken for a child-safety cover; protection around the pool needs its own appropriate design.</p>
<p><a href="https://gb.bio.top/autumnservice2021">Biotop's autumn service guidance</a> combines surface and planted-area care with equipment preparation. Use that as a reminder to review the whole installation. Agree which of your tasks are seasonal, which depend on condition and who will perform them. Plant cutting should follow the actual planting plan rather than a blanket instruction to cut everything back.</p>
<h2>Winter: follow the installed equipment</h2>
<p>Do not assume that every pump runs throughout winter, or that every pump should be removed. <a href="https://www.oase.com/en/pond-and-water-garden/how-to-guides/winterizing-your-water-features">Oase's winter guidance</a> distinguishes frost-resistant equipment from components needing protection. A rating for one component does not establish a winter operating plan for the pool, its pipes and its controls.</p>
<p>Before cold weather, confirm the intended water level, equipment settings, required protection and response to a power cut. Ask what must still be checked when you are away. Winter operation does not itself mean the installation is suitable for winter swimming. Keep the safety arrangements effective when the pool is not in use.</p>
<h2>Know when to ask for help</h2>
<p>Contact the installer when flow does not return to normal after the checks you were shown, when water loss continues, or when equipment behaves unexpectedly. Describe the symptom, equipment model and recent changes. That gives a professional a better starting point than a request for a generic cleaning product.</p>
<p>Planning a new pool? <a href="/en/nature-pools/pricing/">Compare the packages</a> and discuss the ownership tasks alongside the design. For an existing installation, <a href="/en/configure/?service=pool">describe the system and the help you need</a> so we can confirm whether we can assist.</p>
<p>Sources checked: 17 September 2026. Manufacturer examples illustrate why care must match the system; they are not a specification of Faunapoolen package equipment.</p>`;
